CASE
# Beauty
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)la.*mer.*') OR REGEXP_MATCH(SKU,'^CLM.*') THEN "La Mer"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)valmont$') OR REGEXP_MATCH(SKU,'^VMT.*') THEN "Valmont"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)diptyque$') OR REGEXP_MATCH(SKU,'^DIP.*') THEN "Diptyque"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)byredo$') OR REGEXP_MATCH(SKU,'^BYR.*') THEN "Byredo"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)tom_ford$') OR REGEXP_MATCH(SKU,'^TOM.*') THEN "Tom Ford"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)chantecaille$') OR REGEXP_MATCH(SKU,'^CTC.*') THEN "Chantecaille"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)aesop$') OR REGEXP_MATCH(SKU,'^AES.*') THEN "Aesop"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)sensai$') OR REGEXP_MATCH(SKU,'^SAI.*') THEN "Sensai"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)frederic_malle$') OR REGEXP_MATCH(SKU,'^FRM.*') THEN "Frédéric Malle"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)kure_bazaar$') OR REGEXP_MATCH(SKU,'^KBZ.*') THEN "Kure Bazaar"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)arriere_freres$') OR REGEXP_MATCH(SKU,'^CAF.*') THEN "Carrière Frères"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)lola_james_harper$') OR REGEXP_MATCH(SKU,'^LJH.*') THEN "Lola James Harper"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)elixir_des_glaciers$') OR REGEXP_MATCH(SKU,'^EDG.*') THEN "Valmont L'Elixir des Glaciers"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)trudon$') OR REGEXP_MATCH(SKU,'^TRU.*') THEN "Cire Trudon"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)by_kilian$') OR REGEXP_MATCH(SKU,'^BYK.*') THEN "By Kilian"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)claus_porto$') OR REGEXP_MATCH(SKU,'^CLP.*') THEN "Claus Porto"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)tata_harper$') OR REGEXP_MATCH(SKU,'^TAT.*') THEN "Tata Harper"

# Fashion
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)veja$') OR REGEXP_MATCH(SKU,'^VEJ.*') THEN "Veja"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)dior$') OR REGEXP_MATCH(SKU,'^DIO.*') THEN "Dior"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)loewe$') OR REGEXP_MATCH(SKU,'^LOE.*') THEN "Loewe"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)canada.*goose.*') OR REGEXP_MATCH(SKU,'^CNG.*') THEN "Canada Goose"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)burberry$') OR REGEXP_MATCH(SKU,'^BUR.*') THEN "Burberry"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)acne$') OR REGEXP_MATCH(SKU,'^ACN.*') THEN "Acne Studios"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)manu_atelier$') OR REGEXP_MATCH(SKU,'^ATE.*') THEN "Manu Altelier"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)chloe$') OR REGEXP_MATCH(SKU,'^CHL.*') THEN "Chloé"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)balenciaga$') OR REGEXP_MATCH(SKU,'^BAL.*') THEN "Balenciaga"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)miu_miu$') OR REGEXP_MATCH(SKU,'^MIU.*') THEN "Miu Miu"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)self_portrait$') OR REGEXP_MATCH(SKU,'^SLF.*') THEN "Self-Portrait"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)prada$') OR REGEXP_MATCH(SKU,'^PRA.*') THEN "Prada"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)kenzo$') OR REGEXP_MATCH(SKU,'^KEN.*') THEN "Kenzo"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)celine$') OR REGEXP_MATCH(SKU,'^CEL.*') THEN "Celine"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)off_white$') OR REGEXP_MATCH(SKU,'^OFF.*') THEN "Off White"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)marc_jacobs$') OR REGEXP_MATCH(SKU,'^MCJ.*') THEN "Marc Jacobs"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)louis_vuitton$') OR REGEXP_MATCH(SKU,'^LVU.*') THEN "Louis Vuitton"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)bottega_veneta$') OR REGEXP_MATCH(SKU,'^BOT.*') THEN "Bottega Veneta"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)maison_kitsune$') OR REGEXP_MATCH(SKU,'^MKI.*') THEN "Maison Kitsune"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)fendi$') OR REGEXP_MATCH(SKU,'^FEN.*') THEN "Fendi"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)by_far$') OR REGEXP_MATCH(SKU,'^BYF.*') THEN "by Far"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)thom_browne$') OR REGEXP_MATCH(SKU,'^BRW.*') THEN "Thom Browne"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)apc$') OR REGEXP_MATCH(SKU,'^APC.*') THEN "A.P.C."
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)danse_lente$') OR REGEXP_MATCH(SKU,'^DSL.*') THEN "Danse Lente"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)alexander_mcqueen$') OR REGEXP_MATCH(SKU,'^AMQ.*') THEN "Alexander McQueen"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)acqua_di_parma$') OR REGEXP_MATCH(SKU,'^ADP.*') THEN "Acqua di Parma"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)jimmy_choo$') OR REGEXP_MATCH(SKU,'^JCH.*') THEN "Jimmy Choo"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)muun$') OR REGEXP_MATCH(SKU,'^MUU.*') THEN "Muun"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)nike$') OR REGEXP_MATCH(SKU,'^NIK.*') THEN "NIKE"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)annelise_michelson$') OR REGEXP_MATCH(SKU,'^ANM.*') THEN "Annelise Michelson"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)marni$') OR REGEXP_MATCH(SKU,'^MNI.*') THEN "Marni"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)isabel_marant$') OR REGEXP_MATCH(SKU,'^IMA.*') THEN "Isabel Marant"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)yuzefi$') OR REGEXP_MATCH(SKU,'^YUZ.*') THEN "Yuzefi"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)maison_margiela$') OR REGEXP_MATCH(SKU,'^MMM.*') THEN "Maison Margiela"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)demellier$') OR REGEXP_MATCH(SKU,'^DEM.*') THEN "DeMellier"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)gu_de$') OR REGEXP_MATCH(SKU,'^GDE.*') THEN "Gu_De"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)gucci$') OR REGEXP_MATCH(SKU,'^GUC.*') THEN "GUCCI"

END