CASE

    WHEN REGEXP_MATCH(Product Name,'4head.*') THEN "4head"

    WHEN REGEXP_MATCH(Product Name,'(?i)Aveeno.*') THEN "Aveeno"
    WHEN REGEXP_MATCH(Product Name,'Avene.*|Avène.*') THEN "Avene"
    WHEN REGEXP_MATCH(Product Name,'Aussie.*') THEN "Aussie"
    WHEN REGEXP_MATCH(Product Name,'Always.*') THEN "Always"
    WHEN REGEXP_MATCH(Product Name,'Aptamil.*') THEN "Aptamil"
    WHEN REGEXP_MATCH(Product Name,'Ariana Grande.*') THEN "Ariana Grande"

    WHEN REGEXP_MATCH(Product Name,'Bio-Oil.*') THEN "Bio-Oil"
    WHEN REGEXP_MATCH(Product Name,'Bourjois.*') THEN "Bourjois"
    WHEN REGEXP_MATCH(Product Name,'BECCA.*') THEN "BECCA"
    WHEN REGEXP_MATCH(Product Name,'Benefit.*') THEN "Benefit"
    WHEN REGEXP_MATCH(Product Name,'Bioderma.*') THEN "Bioderma"
    WHEN REGEXP_MATCH(Product Name,'Bodyform.*') THEN "Bodyform"
    WHEN REGEXP_MATCH(Product Name,'Bickiepegs.*') THEN "Bickiepegs"
    WHEN REGEXP_MATCH(Product Name,'Baby Ddrops.*') THEN "Baby Ddrops"
    WHEN REGEXP_MATCH(Product Name,'BaByliss.*') THEN "BaByliss"
    WHEN REGEXP_MATCH(Product Name,'Barry M.*') THEN "Barry M"
    WHEN REGEXP_MATCH(Product Name,'Burt.*s Bees.*') THEN "Burt's Bees"
    WHEN REGEXP_MATCH(Product Name,'Botanics.*') THEN "Botanics"
    WHEN REGEXP_MATCH(Product Name,'Braun.*') THEN "Braun"
    WHEN REGEXP_MATCH(Product Name,'Bulldog.*') THEN "Bulldog"
    WHEN REGEXP_MATCH(Product Name,'(?i)Bumble and Bumble.*') THEN "Bumble and Bumble"
    WHEN REGEXP_MATCH(Product Name,'Burberry.*') THEN "Burberry"
    WHEN REGEXP_MATCH(Product Name,'Brush Baby.*') THEN "Brush Baby"
    WHEN REGEXP_MATCH(Product Name,'BOSS.*') THEN "BOSS"
    WHEN REGEXP_MATCH(Product Name,'Batiste.*') THEN "Batiste"
    WHEN REGEXP_MATCH(Product Name,'Baylis & Harding.*') THEN "Baylis & Harding"

    WHEN REGEXP_MATCH(Product Name,'(?i)CHANEL.*') THEN "CHANEL"
    WHEN REGEXP_MATCH(Product Name,'Carex.*') THEN "Carex"
    WHEN REGEXP_MATCH(Product Name,'Cath Kidston.*') THEN "Cath Kidston"
    WHEN REGEXP_MATCH(Product Name,'Centrum.*') THEN "Centrum"
    WHEN REGEXP_MATCH(Product Name,'Champneys.*') THEN "Champneys"
    WHEN REGEXP_MATCH(Product Name,'Clarins.*') THEN "Clarins"
    WHEN REGEXP_MATCH(Product Name,'Curél.*') THEN "Curel"
    WHEN REGEXP_MATCH(Product Name,'Clinique.*') THEN "Clinique"
    WHEN REGEXP_MATCH(Product Name,'Cetaphil.*') THEN "Cetaphil"
    WHEN REGEXP_MATCH(Product Name,'Chloé.*') THEN "Chloe"
    WHEN REGEXP_MATCH(Product Name,'Colgate.*') THEN "Colgate"
    WHEN REGEXP_MATCH(Product Name,'Cow & Gate.*') THEN "Cow & Gate"
    WHEN REGEXP_MATCH(Product Name,'Compeed.*') THEN "Compeed"
    WHEN REGEXP_MATCH(Product Name,'CYO.*') THEN "CYO"
    WHEN REGEXP_MATCH(Product Name,'CeraVe.*') THEN "CeraVe"
    WHEN REGEXP_MATCH(Product Name,'Comvita.*') THEN "Comvita"
    WHEN REGEXP_MATCH(Product Name,'Calpol.*') THEN "Calpol"
    WHEN REGEXP_MATCH(Product Name,'Calvin Klein.*') THEN "Calvin Klein"
    WHEN REGEXP_MATCH(Product Name,'Clean & Clear.*') THEN "Clean & Clear"
    WHEN REGEXP_MATCH(Product Name,'Colab.*') THEN "Colab"
    WHEN REGEXP_MATCH(Product Name,'Collection.*') THEN "Collection"
    WHEN REGEXP_MATCH(Product Name,'Corsodyl.*') THEN "Corsodyl"
    WHEN REGEXP_MATCH(Product Name,'DKNY.*') THEN "DKNY"

    WHEN REGEXP_MATCH(Product Name,'.*(?i)DIOR.*') THEN "DIOR"
    WHEN REGEXP_MATCH(Product Name,'Dettol.*') THEN "Dettol"
    WHEN REGEXP_MATCH(Product Name,'Deep Heat.*') THEN "Deep Heat"
    WHEN REGEXP_MATCH(Product Name,'Dyson.*') THEN "Dyson"
    WHEN REGEXP_MATCH(Product Name,'Dove.*') THEN "Dove"
    WHEN REGEXP_MATCH(Product Name,'Dr.*Jart.*') THEN "Dr.Jart"
    WHEN REGEXP_MATCH(Product Name,'Drunk Elephant.*') THEN "Drunk Elephant"
    WHEN REGEXP_MATCH(Product Name,'Durex.*') THEN "Durex"

    WHEN REGEXP_MATCH(Product Name,'Estee Lauder.*|Estée Lauder.*') THEN "Estee Lauder"
    WHEN REGEXP_MATCH(Product Name,'Eucerin.*') THEN "Eucerin"
    WHEN REGEXP_MATCH(Product Name,'Elizabeth Arden.*') THEN "Elizabeth Arden"
    WHEN REGEXP_MATCH(Product Name,'Embryolisse.*') THEN "Embryolisse"
    WHEN REGEXP_MATCH(Product Name,'eos.*') THEN "eos"
    WHEN REGEXP_MATCH(Product Name,'essie.*') THEN "essie"
    WHEN REGEXP_MATCH(Product Name,'Equazen.*') THEN "Equazen"
    WHEN REGEXP_MATCH(Product Name,'E45.*') THEN "E45"
    WHEN REGEXP_MATCH(Product Name,'Elasticated.*') THEN "Elasticated"
    WHEN REGEXP_MATCH(Product Name,'Elie Saab.*') THEN "Elie Saab"
    WHEN REGEXP_MATCH(Product Name,'Ella.*s Kitchen.*') THEN "Ella's Kitchen"
    WHEN REGEXP_MATCH(Product Name,'Emergen-C.*') THEN "Emergen-C"
    WHEN REGEXP_MATCH(Product Name,'Essie.*') THEN "Essie"

    WHEN REGEXP_MATCH(Product Name,'Fenty.*') THEN "Fenty Beauty"
    WHEN REGEXP_MATCH(Product Name,'(?i)Femfresh.*') THEN "Femfresh"
    WHEN REGEXP_MATCH(Product Name,'Floradix.*') THEN "Floradix"
    WHEN REGEXP_MATCH(Product Name,'Feminax.*') THEN "Feminax"

    WHEN REGEXP_MATCH(Product Name,'Garnier.*') THEN "Garnier"
    WHEN REGEXP_MATCH(Product Name,'Givenchy.*') THEN "Givenchy"
    WHEN REGEXP_MATCH(Product Name,'Guerlain.*') THEN "Guerlain"
    WHEN REGEXP_MATCH(Product Name,'Grow Gorgeous.*') THEN "Grow Gorgeous"
    WHEN REGEXP_MATCH(Product Name,'Gucci.*') THEN "Gucci"
    WHEN REGEXP_MATCH(Product Name,'.*Gold Collagen.*') THEN "Gold Collagen"
    WHEN REGEXP_MATCH(Product Name,'Giorgio Armani.*') THEN "Giorgio Armani"
    WHEN REGEXP_MATCH(Product Name,'Gillette.*') THEN "Gillette"
    WHEN REGEXP_MATCH(Product Name,'(?i)GlamGlow.*') THEN "GlamGlow"

    WHEN REGEXP_MATCH(Product Name,'Hairburst.*') THEN "Hairburst"
    WHEN REGEXP_MATCH(Product Name,'Haliborange.*') THEN "Haliborange"
    WHEN REGEXP_MATCH(Product Name,'HiPP.*') THEN "HiPP"
    WHEN REGEXP_MATCH(Product Name,'(?i)HARRY POTTER.*') THEN "HARRY POTTER"
    WHEN REGEXP_MATCH(Product Name,'Head & Shoulders.*') THEN "Head & Shoulders"
    WHEN REGEXP_MATCH(Product Name,'Herbal Essences.*') THEN "Herbal Essences"
    WHEN REGEXP_MATCH(Product Name,'Hermes.*|Hermès.*') THEN "Hermes"
    WHEN REGEXP_MATCH(Product Name,'Huda Beauty.*') THEN "Huda Beauty"
    WHEN REGEXP_MATCH(Product Name,'Huggies.*') THEN "Huggies"
    WHEN REGEXP_MATCH(Product Name,'Hugo Boss.*') THEN "Hugo Boss"

    WHEN REGEXP_MATCH(Product Name,'IT Cosmetics.*') THEN "IT Cosmetics"
    WHEN REGEXP_MATCH(Product Name,'iWhite.*') THEN "iWhite"
    WHEN REGEXP_MATCH(Product Name,'Imedeen.*') THEN "Imedeen"

    WHEN REGEXP_MATCH(Product Name,'(?i)JOHNSON.*S.*') THEN "JOHNSON'S"
    WHEN REGEXP_MATCH(Product Name,'Jimmy Choo.*') THEN "Jimmy Choo"
    WHEN REGEXP_MATCH(Product Name,'John Frieda.*') THEN "John Frieda"

    WHEN REGEXP_MATCH(Product Name,'Kiddylicious.*') THEN "Kiddylicious"
    WHEN REGEXP_MATCH(Product Name,'Kabrita.*') THEN "Kabrita"
    WHEN REGEXP_MATCH(Product Name,'KVD.*') THEN "KVD"
    WHEN REGEXP_MATCH(Product Name,'Kleenex.*') THEN "Kleenex"

    WHEN REGEXP_MATCH(Product Name,'(?i)Lancôme.*|Lancome.*') THEN "Lancome"
    WHEN REGEXP_MATCH(Product Name,'La Roche-Posay.*') THEN "La Roche-Posay"
    WHEN REGEXP_MATCH(Product Name,'(?i)L.*Oreal.*|Colorista.*') THEN "L'Oreal"
    WHEN REGEXP_MATCH(Product Name,'Lab Series.*') THEN "Lab Series"
    WHEN REGEXP_MATCH(Product Name,'Laura Mercier.*') THEN "Laura Mercier"

    WHEN REGEXP_MATCH(Product Name,'MAC.*') THEN "MAC"
    WHEN REGEXP_MATCH(Product Name,'Montagne Jeunesse.*') THEN "Montagne Jeunesse"
    WHEN REGEXP_MATCH(Product Name,'Mineral.*|Vichy.*') THEN "Vichy"
    WHEN REGEXP_MATCH(Product Name,'Maybelline.*') THEN "Maybelline"
    WHEN REGEXP_MATCH(Product Name,'Monty Bojangles.*') THEN "Monty Bojangles"
    WHEN REGEXP_MATCH(Product Name,'(?i)MARC JACOBS.*') THEN "Marc Jacobs"

    WHEN REGEXP_MATCH(Product Name,'NYX.*') THEN "NYX"
    WHEN REGEXP_MATCH(Product Name,'No7.*') THEN "No7"
    WHEN REGEXP_MATCH(Product Name,'NIVEA.*') THEN "NIVEA"
    WHEN REGEXP_MATCH(Product Name,'Nature.*s.*Bounty.*') THEN "Nature's Bounty"
    WHEN REGEXP_MATCH(Product Name,'NANNYcare.*') THEN "NANNYcare"
    WHEN REGEXP_MATCH(Product Name,'Nasaleze.*') THEN "Nasaleze"

    WHEN REGEXP_MATCH(Product Name,'Olay.*') THEN "Olay"
    WHEN REGEXP_MATCH(Product Name,'Origins.*') THEN "Origins"
    WHEN REGEXP_MATCH(Product Name,'Optrex.*') THEN "Optrex"

    WHEN REGEXP_MATCH(Product Name,'PIXI.*') THEN "PIXI"
    WHEN REGEXP_MATCH(Product Name,'Philips.*') THEN "Philips"
    WHEN REGEXP_MATCH(Product Name,'philosophy.*') THEN "philosophy"
    WHEN REGEXP_MATCH(Product Name,'Pampers.*') THEN "Pampers"
    WHEN REGEXP_MATCH(Product Name,'PaediaSure.*') THEN "PaediaSure"

    WHEN REGEXP_MATCH(Product Name,'Regenerate.*') THEN "Regenerate"
    WHEN REGEXP_MATCH(Product Name,'Real Techniques.*') THEN "Real Techniques"

    WHEN REGEXP_MATCH(Product Name,'Simple.*') THEN "Simple"
    WHEN REGEXP_MATCH(Product Name,'Schwarzkopf.*') THEN "Schwarzkopf"
    WHEN REGEXP_MATCH(Product Name,'Sensodyne.*') THEN "Sensodyne"
    WHEN REGEXP_MATCH(Product Name,'Soap & Glory.*') THEN "Soap & Glory"
    WHEN REGEXP_MATCH(Product Name,'SMA.*') THEN "SMA"
    WHEN REGEXP_MATCH(Product Name,'Sambucol.*') THEN "Sambucol"

    WHEN REGEXP_MATCH(Product Name,'Too Faced.*') THEN "Too Faced"
    WHEN REGEXP_MATCH(Product Name,'The Ordinary.*') THEN "The Ordinary"
    WHEN REGEXP_MATCH(Product Name,'Tresemme.*') THEN "Tresemme"
    WHEN REGEXP_MATCH(Product Name,'Toni&Guy.*') THEN "Toni & Guy"
    WHEN REGEXP_MATCH(Product Name,'this works.*') THEN "this works"
    WHEN REGEXP_MATCH(Product Name,'Tampax.*') THEN "Tampax"

    WHEN REGEXP_MATCH(Product Name,'Urban Decay.*') THEN "Urban Decay"

    WHEN REGEXP_MATCH(Product Name,'Versace.*') THEN "Versace"
    WHEN REGEXP_MATCH(Product Name,'Veet.*') THEN "Veet"
    WHEN REGEXP_MATCH(Product Name,'Vaseline.*') THEN "Vaseline"
    WHEN REGEXP_MATCH(Product Name,'Vitabiotics.*') THEN "Vitabiotics"
    WHEN REGEXP_MATCH(Product Name,'Voost.*') THEN "Voost"
    WHEN REGEXP_MATCH(Product Name,'Viviscal.*') THEN "Viviscal"

    WHEN REGEXP_MATCH(Product Name,'(?i)wet n wild.*') THEN "wet n wild"
    WHEN REGEXP_MATCH(Product Name,'Wet Ones.*') THEN "Wet Ones"
    WHEN REGEXP_MATCH(Product Name,'Westlab.*') THEN "Westlab"
    WHEN REGEXP_MATCH(Product Name,'Wilkinson.*') THEN "Wilkinson"
    WHEN REGEXP_MATCH(Product Name,'Waterpik.*') THEN "Waterpik"
    WHEN REGEXP_MATCH(Product Name,'Weleda.*') THEN "Weleda"
    WHEN REGEXP_MATCH(Product Name,'Wellwoman.*') THEN "Wellwoman"

    WHEN REGEXP_MATCH(Product Name,'YSL.*|Yves Saint Laurent.*') THEN "YSL"
    WHEN REGEXP_MATCH(Product Name,'Yankee.*') THEN "Yankee"

    WHEN REGEXP_MATCH(Product Name,'Boots.*') THEN "Boots"

END