CASE
    WHEN REGEXP_MATCH(cg_code,'.*BEAUTY.*|.*FRAGRANCE.*|.*PHOTO.*|.*DEFAULT.*|.*GIFT.*') THEN "BEAUTY"
    WHEN REGEXP_MATCH(cg_code,'.*BABY.*') THEN "BABY"
    WHEN REGEXP_MATCH(cg_code,'.*TOILETRIES.*') THEN "TOILETRIES"
    WHEN REGEXP_MATCH(cg_code,'.*HEALTH.*') THEN "HEALTH"
END