CASE
  WHEN REGEXP_MATCH(Product Name, '(?i)GUCCI.*') THEN "GUCCI"
  WHEN REGEXP_MATCH(Product Name, '(?i)Canada Goose.*') THEN "Canada Goose"
  WHEN REGEXP_MATCH(Product Name, '(?i)KENZO.*') THEN "KENZO"
  WHEN REGEXP_MATCH(Product Name, '(?i)Vans.*') THEN "Vans"
  WHEN REGEXP_MATCH(Product Name, '(?i)Champion.*') THEN "Champion"
  WHEN REGEXP_MATCH(Product Name, '(?i)Golden Goose.*') THEN "Golden Goose"
  WHEN REGEXP_MATCH(Product Name, '(?i)Alexander Wang.*') THEN "Alexander Wang"
  WHEN REGEXP_MATCH(Product Name, '(?i)The North Face.*') THEN "The North Face"
  WHEN REGEXP_MATCH(Product Name, '(?i)Coach.*') THEN "Coach"
  WHEN REGEXP_MATCH(Product Name, '(?i)Shrimps.*') THEN "Shrimps"
  WHEN REGEXP_MATCH(Product Name, '(?i)AMI.*') THEN "AMI"
  WHEN REGEXP_MATCH(Product Name, '(?i)Acne Studios.*') THEN "Acne Studios"
  WHEN REGEXP_MATCH(Product Name, '(?i)Vivienne Westwood.*') THEN "Vivienne Westwood"
  WHEN REGEXP_MATCH(Product Name, '(?i)Marc Jacobs.*') THEN "Marc Jacobs"
  WHEN REGEXP_MATCH(Product Name, '(?i)Yuzefi.*') THEN "Yuzefi"
  WHEN REGEXP_MATCH(Product Name, '(?i)Dr. Martens.*') THEN "Dr. Martens"
  WHEN REGEXP_MATCH(Product Name, '(?i)Barbour.*') THEN "Barbour"
  WHEN REGEXP_MATCH(Product Name, '(?i)UGG.*') THEN "UGG"
  WHEN REGEXP_MATCH(Product Name, '(?i)Ganni.*') THEN "Ganni"
  WHEN REGEXP_MATCH(Product Name, '(?i)by FAR.*') THEN "by FAR"
  WHEN REGEXP_MATCH(Product Name, '(?i)McQ.*') THEN "Alexander McQueen"
  WHEN REGEXP_MATCH(Product Name, '(?i)Wee Gallery.*') THEN "Wee Gallery"
  WHEN REGEXP_MATCH(Product Name, '(?i)Calvin Klein.*') THEN "Calvin Klein"
  WHEN REGEXP_MATCH(Product Name, '(?i)Bally.*') THEN "Bally"
  WHEN REGEXP_MATCH(Product Name, '(?i)A.P.C.*') THEN "A.P.C."
  WHEN REGEXP_MATCH(Product Name, '(?i)Saint Laurent.*') THEN "Saint Laurent"
  WHEN REGEXP_MATCH(Product Name, '(?i)adidas.*|(?i)Stella McCartney.*') THEN "adidas"
  WHEN REGEXP_MATCH(Product Name, '(?i)Self-Portrait.*') THEN "Self-Portrait"
  WHEN REGEXP_MATCH(Product Name, '(?i)RAINS.*') THEN "RAINS"
  WHEN REGEXP_MATCH(Product Name, '(?i)BKLYN.*') THEN "BKLYN"
  WHEN REGEXP_MATCH(Product Name, '(?i)Danse Lente.*') THEN "Danse Lente"
  WHEN REGEXP_MATCH(Product Name, '(?i)JW Anderson.*') THEN "JW Anderson"
  WHEN REGEXP_MATCH(Product Name, '.*(?i)MICHAEL KORS.*') THEN "MICHAEL KORS"
  WHEN REGEXP_MATCH(Product Name, '(?i)See By Chloe.*') THEN "See By Chloé"
  WHEN REGEXP_MATCH(Product Name, '(?i)Fjallraven.*') THEN "Fjällräven"
  WHEN REGEXP_MATCH(Product Name, '(?i)MSGM.*') THEN "MSGM"
  WHEN REGEXP_MATCH(Product Name, '(?i)meli melo.*') THEN "meli melo"
  WHEN REGEXP_MATCH(Product Name, '.*(?i)Ralph Lauren.*') THEN "Ralph Lauren"
  WHEN REGEXP_MATCH(Product Name, '(?i)Aspinal of London.*') THEN "Aspinal of London"
  WHEN REGEXP_MATCH(Product Name, '(?i)Matthew Miller.*') THEN "Matthew Miller"
  WHEN REGEXP_MATCH(Product Name, '(?i)FILA.*') THEN "FILA"
  WHEN REGEXP_MATCH(Product Name, '(?i)Grenson.*') THEN "Grenson"
  WHEN REGEXP_MATCH(Product Name, '(?i)Mulberry.*') THEN "Mulberry"
  WHEN REGEXP_MATCH(Product Name, '(?i)Chloe.*') THEN "Chloé"
  WHEN REGEXP_MATCH(Product Name, '.*(?i)Maison Margiela.*') THEN "Maison Margiela"
  WHEN REGEXP_MATCH(Product Name, '(?i)Ray-Ban.*') THEN "Ray-Ban"
  WHEN REGEXP_MATCH(Product Name, '(?i)Mackage.*') THEN "Mackage"
  WHEN REGEXP_MATCH(Product Name, '(?i)Veja.*') THEN "Veja"
  WHEN REGEXP_MATCH(Product Name, '(?i)Emporio Armani.*') THEN "Emporio Armani"
  WHEN REGEXP_MATCH(Product Name, '(?i)Y-3.*') THEN "Y-3"
  WHEN REGEXP_MATCH(Product Name, '(?i)HUGO.*') THEN "HUGO"
  WHEN REGEXP_MATCH(Product Name, '(?i)Paul Smith.*') THEN "Paul Smith"
  WHEN REGEXP_MATCH(Product Name, '(?i)Tod&#039;s.*') THEN "Tod's"
  WHEN REGEXP_MATCH(Product Name, '(?i)Balmain.*') THEN "Balmain"
  WHEN REGEXP_MATCH(Product Name, '(?i)Frame.*') THEN "Frame"
  WHEN REGEXP_MATCH(Product Name, '(?i)Lacoste.*') THEN "Lacoste"
  WHEN REGEXP_MATCH(Product Name, '(?i)Versus Versace.*') THEN "Versus Versace"
  WHEN REGEXP_MATCH(Product Name, '(?i)Karl Lagerfeld.*') THEN "Karl Lagerfeld"
  WHEN REGEXP_MATCH(Product Name, '(?i)Tom Ford.*') THEN "Tom Ford"
  WHEN REGEXP_MATCH(Product Name, '(?i)Furla.*') THEN "Furla"
  WHEN REGEXP_MATCH(Product Name, '.*(?i)Paul Smith.*') THEN "Paul Smith"
  WHEN REGEXP_MATCH(Product Name, '(?i)Neil Barrett.*') THEN "Neil Barrett"
  WHEN REGEXP_MATCH(Product Name, '(?i)Woolrich.*') THEN "Woolrich"
  WHEN REGEXP_MATCH(Product Name, '(?i)Charlotte Olympia.*') THEN "Charlotte Olympia"
  WHEN REGEXP_MATCH(Product Name, '(?i)Converse.*') THEN "Converse"
  WHEN REGEXP_MATCH(Product Name, '(?i)Dsquared2.*') THEN "Dsquared2"
  WHEN REGEXP_MATCH(Product Name, '(?i)Axel Arigato.*') THEN "Axel Arigato"
  WHEN REGEXP_MATCH(Product Name, '(?i)The Ordinary.*') THEN "The Ordinary"
  WHEN REGEXP_MATCH(Product Name, 'REN.*') THEN "REN"
  WHEN REGEXP_MATCH(Product Name, '(?i)Yuul Yie.*') THEN "Yuul Yie"
  WHEN REGEXP_MATCH(Product Name, '(?i)Maison Kitsune.*') THEN "Maison Kitsune"
  WHEN REGEXP_MATCH(Product Name, '(?i)Asics.*') THEN "Asics"
  WHEN REGEXP_MATCH(Product Name, '(?i)Anni Lu.*') THEN "Anni Lu"
  WHEN REGEXP_MATCH(Product Name, 'YMC.*') THEN "YMC"
  WHEN REGEXP_MATCH(Product Name, '(?i)Isabel Marant.*') THEN "Isabel Marant"
  WHEN REGEXP_MATCH(Product Name, '(?i)Dorateymur.*') THEN "Dorateymur"
  WHEN REGEXP_MATCH(Product Name, '(?i)Cire Trudon.*') THEN "Cire Trudon"
  WHEN REGEXP_MATCH(Product Name, '(?i)Lanvin.*') THEN "Lanvin"
  WHEN REGEXP_MATCH(Product Name, '(?i)Joshua Sanders.*') THEN "Joshua Sanders"
  WHEN REGEXP_MATCH(Product Name, '(?i)J Brand.*') THEN "J Brand"
  WHEN REGEXP_MATCH(Product Name, '(?i)Drôle de Monsieur.*') THEN "Drôle de Monsieur"
  WHEN REGEXP_MATCH(Product Name, '(?i)Ash.*') THEN "Ash"
  WHEN REGEXP_MATCH(Product Name, '(?i)S&#039;well.*') THEN "S'well"
  WHEN REGEXP_MATCH(Product Name, '(?i)Universal Works.*') THEN "Universal Works"
END
