CASE
    WHEN REGEXP_MATCH(Product Name,'111SKIN.*') THEN "111SKIN"
    
    WHEN REGEXP_MATCH(Product Name,'Augustinus Bader.*') THEN "Augustinus Bader"
    WHEN REGEXP_MATCH(Product Name,'Anastasia Beverly Hills.*') THEN "Anastasia Beverly Hills"
    WHEN REGEXP_MATCH(Product Name,'Alpha-H.*') THEN "Alpha-H"
    WHEN REGEXP_MATCH(Product Name,'Aesop.*') THEN "Aesop"
    WHEN REGEXP_MATCH(Product Name,'Aurelia Probiotic Skincare.*') THEN "Aurelia Probiotic Skincare"
    WHEN REGEXP_MATCH(Product Name,'Algenist.*') THEN "Algenist"
    WHEN REGEXP_MATCH(Product Name,'African Botanics.*') THEN "African Botanics"

    WHEN REGEXP_MATCH(Product Name,'BECCA.*') THEN "BECCA"
    WHEN REGEXP_MATCH(Product Name,'BY TERRY.*') THEN "BY TERRY"
    WHEN REGEXP_MATCH(Product Name,'Beautyblender.*') THEN "Beautyblender"
    WHEN REGEXP_MATCH(Product Name,'Benefit.*') THEN "Benefit"
    WHEN REGEXP_MATCH(Product Name,'Briogeo.*') THEN "Briogeo"
    WHEN REGEXP_MATCH(Product Name,'Bjork & Berries.*') THEN "Bjork & Berries"
    WHEN REGEXP_MATCH(Product Name,'BLEACH LONDON.*') THEN "BLEACH LONDON"
    WHEN REGEXP_MATCH(Product Name,'Biossance.*') THEN "Biossance"
    WHEN REGEXP_MATCH(Product Name,'Bouclème.*') THEN "Bouclème"

    WHEN REGEXP_MATCH(Product Name,'Charlotte.*Tilbury.*') THEN "Charlotte Tilbury"
    WHEN REGEXP_MATCH(Product Name,'Caudalie.*') THEN "Caudalie"
    WHEN REGEXP_MATCH(Product Name,'Chantecaille.*') THEN "Chantecaille"
    WHEN REGEXP_MATCH(Product Name,'Christian Louboutin.*') THEN "Christian Louboutin"
    WHEN REGEXP_MATCH(Product Name,'Cire Trudon.*') THEN "Cire Trudon"
    WHEN REGEXP_MATCH(Product Name,'Costa Brazil.*') THEN "Costa Brazil"

    WHEN REGEXP_MATCH(Product Name,'Drunk.*Elephant.*') THEN "Drunk Elephant"
    WHEN REGEXP_MATCH(Product Name,'Decree.*') THEN "Decree"
    WHEN REGEXP_MATCH(Product Name,'Dr.* Jart.*') THEN "Dr. Jart+"
    WHEN REGEXP_MATCH(Product Name,'Dr.* Barbara Sturm.*') THEN "Dr. Barbara Sturm"
    WHEN REGEXP_MATCH(Product Name,'Davines.*') THEN "Davines"
    WHEN REGEXP_MATCH(Product Name,'Dr.* Dennis Gross.*') THEN "Dr. Dennis Gross"
    WHEN REGEXP_MATCH(Product Name,'Dizziak.*') THEN "Dizziak"
    WHEN REGEXP_MATCH(Product Name,'DCL.*') THEN "DCL"

    WHEN REGEXP_MATCH(Product Name,'Erno Laszlo.*') THEN "Erno Laszlo"
    WHEN REGEXP_MATCH(Product Name,'Emma Hardie.*') THEN "Emma Hardie"
    WHEN REGEXP_MATCH(Product Name,'Eve Lom.*') THEN "Eve Lom"
    WHEN REGEXP_MATCH(Product Name,'Embryolisse.*') THEN "Embryolisse"
    WHEN REGEXP_MATCH(Product Name,'Escentric.*') THEN "Escentric"

    WHEN REGEXP_MATCH(Product Name,'fresh.*') THEN "fresh"
    WHEN REGEXP_MATCH(Product Name,'FARMACY.*') THEN "FARMACY"
    WHEN REGEXP_MATCH(Product Name,'Four Sigmatic.*') THEN "Four Sigmatic"
    WHEN REGEXP_MATCH(Product Name,'frank body.*') THEN "frank body"

    WHEN REGEXP_MATCH(Product Name,'Goldfaden MD.*') THEN "Goldfaden MD"
    WHEN REGEXP_MATCH(Product Name,'Glow Recipe.*') THEN "Glow Recipe"
    WHEN REGEXP_MATCH(Product Name,'ghd.*') THEN "ghd"

    WHEN REGEXP_MATCH(Product Name,'Huda.*Beauty.*') THEN "Huda Beauty"
    WHEN REGEXP_MATCH(Product Name,'Hourglass.*') THEN "Hourglass"
    WHEN REGEXP_MATCH(Product Name,'Herbivore.*') THEN "Herbivore"

    WHEN REGEXP_MATCH(Product Name,'IT Cosmetics.*') THEN "IT Cosmetics"
    WHEN REGEXP_MATCH(Product Name,'Isle of Paradise.*') THEN "Isle of Paradise"
    WHEN REGEXP_MATCH(Product Name,'ICONIC LONDON.*') THEN "ICONIC LONDON"
    WHEN REGEXP_MATCH(Product Name,'Indie Lee.*') THEN "Indie Lee"

    WHEN REGEXP_MATCH(Product Name,'Jo Loves.*') THEN "Jo Loves"
    WHEN REGEXP_MATCH(Product Name,'Jouer Cosmetics.*') THEN "Jouer Cosmetics"

    WHEN REGEXP_MATCH(Product Name,'Kevyn Aucoin.*') THEN "Kevyn Aucoin"
    WHEN REGEXP_MATCH(Product Name,'KORA Organics.*') THEN "KORA Organics"
    WHEN REGEXP_MATCH(Product Name,'Kai.*') THEN "Kai"
    WHEN REGEXP_MATCH(Product Name,'Kate Somerville.*') THEN "Kate Somerville"
    WHEN REGEXP_MATCH(Product Name,'Kilian.*') THEN "Kilian"
    WHEN REGEXP_MATCH(Product Name,'Kitsch.*') THEN "Kitsch"
    WHEN REGEXP_MATCH(Product Name,'Kosas.*') THEN "Kosas"

    WHEN REGEXP_MATCH(Product Name,'Le Labo.*') THEN "Le Labo"
    WHEN REGEXP_MATCH(Product Name,'Laura Mercier.*') THEN "Laura Mercier"
    WHEN REGEXP_MATCH(Product Name,'Leonor Greyl.*') THEN "Leonor Greyl"
    WHEN REGEXP_MATCH(Product Name,'Living Proof.*') THEN "Living Proof"
    WHEN REGEXP_MATCH(Product Name,'Lime Crime.*') THEN "Lime Crime"
    WHEN REGEXP_MATCH(Product Name,'Lanolips.*') THEN "Lanolips"
    WHEN REGEXP_MATCH(Product Name,'LIXIRSKIN.*') THEN "LIXIRSKIN"
    WHEN REGEXP_MATCH(Product Name,'Legology.*') THEN "Legology"
    WHEN REGEXP_MATCH(Product Name,'Lumity.*') THEN "Lumity"

    WHEN REGEXP_MATCH(Product Name,'MALIN.*GOETZ.*') THEN "MALIN + GOETZ"
    WHEN REGEXP_MATCH(Product Name,'Maison Margiela.*') THEN "Maison Margiela"
    WHEN REGEXP_MATCH(Product Name,'Morphe.*') THEN "Morphe"
    WHEN REGEXP_MATCH(Product Name,'MOLTON BROWN.*') THEN "MOLTON BROWN"
    WHEN REGEXP_MATCH(Product Name,'MARA.*') THEN "MARA"
    WHEN REGEXP_MATCH(Product Name,'Medik8.*') THEN "Medik8"
    WHEN REGEXP_MATCH(Product Name,'MEMO PARIS.*') THEN "MEMO PARIS"
    WHEN REGEXP_MATCH(Product Name,'MV Skintherapy.*') THEN "MV Skintherapy"
    WHEN REGEXP_MATCH(Product Name,'Milk Makeup.*') THEN "Milk Makeup"
    WHEN REGEXP_MATCH(Product Name,'Murad.*') THEN "Murad"

    WHEN REGEXP_MATCH(Product Name,'NARS.*') THEN "NARS"
    WHEN REGEXP_MATCH(Product Name,'NatureLab TOKYO.*') THEN "NatureLab TOKYO"
    WHEN REGEXP_MATCH(Product Name,'Nuxe.*') THEN "Nuxe"
    WHEN REGEXP_MATCH(Product Name,'Natasha Denona.*') THEN "Natasha Denona"
    WHEN REGEXP_MATCH(Product Name,'NYX.*') THEN "NYX"
    WHEN REGEXP_MATCH(Product Name,'NIOD.*') THEN "NIOD"

    WHEN REGEXP_MATCH(Product Name,'Oskia.*') THEN "Oskia"
    WHEN REGEXP_MATCH(Product Name,'Omorovicza.*') THEN "Omorovicza"
    WHEN REGEXP_MATCH(Product Name,'Oribe.*') THEN "Oribe"
    WHEN REGEXP_MATCH(Product Name,'OLAPLEX.*') THEN "OLAPLEX"
    WHEN REGEXP_MATCH(Product Name,'OUAI.*') THEN "OUAI"
    WHEN REGEXP_MATCH(Product Name,'Odacite.*') THEN "Odacite"

    WHEN REGEXP_MATCH(Product Name,'Philip Kingsley.*') THEN "Philip Kingsley"
    WHEN REGEXP_MATCH(Product Name,"PAULA'S CHOICE.*") THEN "PAULA'S CHOICE"
    WHEN REGEXP_MATCH(Product Name,"Pixi.*") THEN "Pixi"
    WHEN REGEXP_MATCH(Product Name,"Patchology.*") THEN "Patchology"
    WHEN REGEXP_MATCH(Product Name,"Peter Thomas Roth.*") THEN "Peter Thomas Roth"
    WHEN REGEXP_MATCH(Product Name,"Plenaire.*") THEN "Plenaire"

    WHEN REGEXP_MATCH(Product Name,"REN CLEAN SKINCARE.*") THEN "REN CLEAN SKINCARE"
    WHEN REGEXP_MATCH(Product Name,"RevitaLash.*") THEN "RevitaLash"
    WHEN REGEXP_MATCH(Product Name,"rahua.*") THEN "rahua"

    WHEN REGEXP_MATCH(Product Name,'Saturday Skin.*') THEN "Saturday Skin"
    WHEN REGEXP_MATCH(Product Name,'SUQQU.*') THEN "SUQQU"
    WHEN REGEXP_MATCH(Product Name,'skyn ICELAND.*') THEN "skyn ICELAND"
    WHEN REGEXP_MATCH(Product Name,'Sunday Riley.*') THEN "Sunday Riley"
    WHEN REGEXP_MATCH(Product Name,'Sol de Janeiro.*') THEN "Sol de Janeiro"
    WHEN REGEXP_MATCH(Product Name,'St.* Tropez.*') THEN "St. Tropez"
    WHEN REGEXP_MATCH(Product Name,'Slip.*') THEN "Slip"
    WHEN REGEXP_MATCH(Product Name,'Shani Darden.*') THEN "Shani Darden"
    WHEN REGEXP_MATCH(Product Name,'Supergoop.*') THEN "Supergoop"
    WHEN REGEXP_MATCH(Product Name,'Sachajuan.*') THEN "Sachajuan"
    WHEN REGEXP_MATCH(Product Name,'Sana Jardin.*') THEN "Sana Jardin"
    WHEN REGEXP_MATCH(Product Name,'Sand&Sky.*') THEN "Sand & Sky"
    WHEN REGEXP_MATCH(Product Name,'Shiseido.*') THEN "Shiseido"
    WHEN REGEXP_MATCH(Product Name,'Soleil Toujours.*') THEN "Soleil Toujours"
    WHEN REGEXP_MATCH(Product Name,'Surratt.*') THEN "Surratt"

    WHEN REGEXP_MATCH(Product Name,'The.*Ordinary.*') THEN "The Ordinary"
    WHEN REGEXP_MATCH(Product Name,'THE INKEY LIST.*') THEN "THE INKEY LIST"
    WHEN REGEXP_MATCH(Product Name,'Tata Harper.*') THEN "Tata Harper"
    WHEN REGEXP_MATCH(Product Name,'Too Faced.*') THEN "Too Faced"

    WHEN REGEXP_MATCH(Product Name,'Urban Decay.*') THEN "Urban Decay"
    WHEN REGEXP_MATCH(Product Name,'U Beauty.*') THEN "U Beauty"

    WHEN REGEXP_MATCH(Product Name,'VOTARY.*') THEN "VOTARY"
    WHEN REGEXP_MATCH(Product Name,'Verso.*') THEN "Verso"
    WHEN REGEXP_MATCH(Product Name,'Virtue.*') THEN "Virtue"
    WHEN REGEXP_MATCH(Product Name,'VENeffect.*') THEN "VENeffect"
    WHEN REGEXP_MATCH(Product Name,'Viseart.*') THEN "Viseart"
    WHEN REGEXP_MATCH(Product Name,"Vintner's Daughter.*") THEN "Vintner's Daughter"

    WHEN REGEXP_MATCH(Product Name,'Wishful.*') THEN "Wishful"
    WHEN REGEXP_MATCH(Product Name,'Wander Beauty.*') THEN "Wander Beauty"
    WHEN REGEXP_MATCH(Product Name,'WelleCo.*') THEN "WelleCo"

    WHEN REGEXP_MATCH(Product Name,'Yu Ling Rollers.*') THEN "Yu Ling Rollers"

    WHEN REGEXP_MATCH(Product Name,'Zelens.*') THEN "Zelens"
    WHEN REGEXP_MATCH(Product Name,'ZOEVA.*') THEN "ZOEVA"

    WHEN REGEXP_MATCH(Product Name,'Cult Beauty.*') THEN "Cult Beauty"
END