CASE
	WHEN REGEXP_MATCH(StoreName,'LOOKFANTASTIC 英国官网|Lookfantastic英国官网') THEN "Lookfantastic UK"
    WHEN REGEXP_MATCH(StoreName,'Lookfantastic法国官网') THEN "Lookfantastic FR"
    WHEN REGEXP_MATCH(StoreName,'Amazon英国亚马逊') THEN "Amazon UK"
    WHEN REGEXP_MATCH(StoreName,'Dealmoon英国省钱快报') THEN "Dealmoon UK"
    WHEN REGEXP_MATCH(StoreName,'Nike耐克英国官网') THEN "Nike UK"
    WHEN REGEXP_MATCH(StoreName,'(?i)adidas英国官网|(?i)adidas.*UK') THEN "adidas UK"
    WHEN REGEXP_MATCH(StoreName,'Urban Outfitters英国官网') THEN "Urban Outfitters UK"
    WHEN REGEXP_MATCH(StoreName,'Estee Lauder英国官网') THEN "Estee Lauder UK"
    WHEN REGEXP_MATCH(StoreName,'圆通速递英国站') THEN "YTO Express"
    WHEN REGEXP_MATCH(StoreName,'Harvey Nichols & Co Ltd|Harvey Nichols &amp; Co Ltd') THEN "Harvey Nichols"
    WHEN REGEXP_MATCH(StoreName,'UNIQLO优衣库') THEN "Uniqlo"
    WHEN REGEXP_MATCH(StoreName,'Matchesfashion 英国官网') THEN "Matchesfashion UK"
    WHEN REGEXP_MATCH(StoreName,'The Royal Mint皇家铸币厂') THEN "The Royal Mint"
    WHEN REGEXP_MATCH(StoreName,'Bobbi Brown英国官网') THEN "Bobbi Brown UK"
    WHEN REGEXP_MATCH(StoreName,'La Mer.*英国.*') THEN "La Mer UK"
    WHEN REGEXP_MATCH(StoreName,'Mankind.*英国官网') THEN "Mankind UK"
    WHEN REGEXP_MATCH(StoreName,'(?i)24s|24 SÈVRES') THEN "24S"
    WHEN REGEXP_MATCH(StoreName,'Asics英国官网') THEN "Asics UK"
    WHEN REGEXP_MATCH(StoreName,'Benefit Cosmetics英国官网') THEN "Benefit Cosmetics UK"
    WHEN REGEXP_MATCH(StoreName,'Bose英国官网') THEN "Bose UK"
    WHEN REGEXP_MATCH(StoreName,'Burberry英国官网') THEN "Burberry UK"
    WHEN REGEXP_MATCH(StoreName,'Chatime日出茶太') THEN "Chatime"
    WHEN REGEXP_MATCH(StoreName,'Clarins英国官网') THEN "Clarins UK"
    WHEN REGEXP_MATCH(StoreName,'Clarks英国官网') THEN "Clarks UK"
    WHEN REGEXP_MATCH(StoreName,'Darphin英国官网') THEN "Darphin UK"
    WHEN REGEXP_MATCH(StoreName,'Dr.Martens英国官网') THEN "Dr.Martens UK"
    WHEN REGEXP_MATCH(StoreName,'Dyson英国官网') THEN "Dyson UK"
    WHEN REGEXP_MATCH(StoreName,'Forzieri英国官网') THEN "Forzieri UK"
    WHEN REGEXP_MATCH(StoreName,'HP 惠普英国官网|HP') THEN "HP UK"
    WHEN REGEXP_MATCH(StoreName,'(?i)Happy Lam.* Hot Pot') THEN "Happy Lamb Hot Pot"
    WHEN REGEXP_MATCH(StoreName,'Hermes爱马仕官网') THEN "Hermes"
    WHEN REGEXP_MATCH(StoreName,'HungryPanda.*') THEN "Hungry Panda"
    WHEN REGEXP_MATCH(StoreName,'Hunter 英国官网') THEN "Hunter UK"
    WHEN REGEXP_MATCH(StoreName,'IKEA英国官网') THEN "IKEA UK"
    WHEN REGEXP_MATCH(StoreName,'(?i)JomaShop') THEN "JomaShop"
    WHEN REGEXP_MATCH(StoreName,'Jurlique英国官网') THEN "Jurlique UK"
    WHEN REGEXP_MATCH(StoreName,'Kate Spade英国官网') THEN "Kate Spade UK"
    WHEN REGEXP_MATCH(StoreName,'LOOKFANTASTIC 中国官网') THEN "Lookfantastic CN"
    WHEN REGEXP_MATCH(StoreName,'LOOKFANTASTIC.*法国官网') THEN "Lookfantastic FR"
    WHEN REGEXP_MATCH(StoreName,'Moschino英国官网') THEN "Moschino CN"
    WHEN REGEXP_MATCH(StoreName,'NET-A-PORTER.*') THEN "NET-A-PORTER UK"
    WHEN REGEXP_MATCH(StoreName,'Next英国官网') THEN "Next UK"
    WHEN REGEXP_MATCH(StoreName,'Nintendo英国官网|Nintendo Official UK Store|Nintendo eShop') THEN "Nintendo UK"
    WHEN REGEXP_MATCH(StoreName,'Origins英国官网') THEN "Origins UK"
    WHEN REGEXP_MATCH(StoreName,'Reebok英国官网') THEN "Reebok UK"
    WHEN REGEXP_MATCH(StoreName,'(?i)boots') THEN "Boots"
    WHEN REGEXP_MATCH(StoreName,'Apple.*') THEN "Apple UK"
    WHEN REGEXP_MATCH(StoreName,'Claires英国官网') THEN "Claires UK"
    WHEN REGEXP_MATCH(StoreName,'Dior UK.*') THEN "Dior UK & Ireland"
    WHEN REGEXP_MATCH(StoreName,'FORTNUM.*MASON') THEN "FORTNUM & MASON"
    WHEN REGEXP_MATCH(StoreName,'Folli Follie英国官网') THEN "Folli Follie UK"
    WHEN REGEXP_MATCH(StoreName,'Fondue Factory 火宴山') THEN "Fondue Factory"
    WHEN REGEXP_MATCH(StoreName,'H&amp;M UK|H&M UK') THEN "H&M UK"
    WHEN REGEXP_MATCH(StoreName,'Hotel.*Chocolat') THEN "Hotel Chocolat"
    WHEN REGEXP_MATCH(StoreName,'Kiehl.*UK') THEN "Kiehl's UK"
    WHEN REGEXP_MATCH(StoreName,'London Chinatown 伦敦中国城') THEN "London Chinatown"
    WHEN REGEXP_MATCH(StoreName,'Louis Vuitton英国') THEN "Louis Vuitton UK"
    WHEN REGEXP_MATCH(StoreName,'MCM.*UK') THEN "MCM UK"
    WHEN REGEXP_MATCH(StoreName,'Manuka.*Pharm') THEN "Manuka Pharm"
    WHEN REGEXP_MATCH(StoreName,'Marks.*Spencer') THEN "Marks & Spencer"
    WHEN REGEXP_MATCH(StoreName,'(?i)Pandora') THEN "Pandora"
    WHEN REGEXP_MATCH(StoreName,'Premier Laser.*Skin') THEN "Premier Laser & Skin"
    WHEN REGEXP_MATCH(StoreName,'Samsung英国官网') THEN "Samsung UK"
    WHEN REGEXP_MATCH(StoreName,'(?i)Secret.*Sales') THEN "Secret Sales"
    WHEN REGEXP_MATCH(StoreName,'Shopbop英国官网') THEN "Shopbop UK"
    WHEN REGEXP_MATCH(StoreName,'Ticketmaster.*') THEN "Ticketmaster"
    WHEN REGEXP_MATCH(StoreName,'(?i)eBay英国官网') THEN "eBay UK"
    WHEN REGEXP_MATCH(StoreName,'(?i)harrods') THEN "Harrods"
    WHEN REGEXP_MATCH(StoreName,'smashbox英国官网') THEN "Smashbox UK"
    WHEN REGEXP_MATCH(StoreName,'warehouse英国官网') THEN "Warehouse UK"
    WHEN REGEXP_MATCH(StoreName,'英国WINISHOP日韩美妆网') THEN "Winishop UK"

    ELSE StoreName
END