CASE
	WHEN REGEXP_MATCH(Product Name,'^SkinCeuticals.*') THEN "SkinCeuticals"
    WHEN REGEXP_MATCH(Product Name,'^(?i)NeoStrata.*') THEN "NeoStrata"
    WHEN REGEXP_MATCH(Product Name,'^Oxygenetix.*') THEN "Oxygenetix"
    WHEN REGEXP_MATCH(Product Name,'^iS Clinical.*') THEN "iS Clinical"
    WHEN REGEXP_MATCH(Product Name,'^BIOEFFECT.*') THEN "BIOEFFECT"
    WHEN REGEXP_MATCH(Product Name,'^The Ordinary.*') THEN "The Ordinary"
    WHEN REGEXP_MATCH(Product Name,'^Mesoestetic.*') THEN "Mesoestetic"
    WHEN REGEXP_MATCH(Product Name,'^Glo.*') THEN "Glo Skin Beauty"
    WHEN REGEXP_MATCH(Product Name,'^Proto-col.*') THEN "Proto-col"
    WHEN REGEXP_MATCH(Product Name,'^CeraVe.*') THEN "CeraVe"
    WHEN REGEXP_MATCH(Product Name,'^Sesderma.*') THEN "Sesderma"
    WHEN REGEXP_MATCH(Product Name,'^Endocare.*') THEN "Endocare"
    WHEN REGEXP_MATCH(Product Name,'^Medik8.*') THEN "Medik8"
    WHEN REGEXP_MATCH(Product Name,'^Dr Sebagh.*') THEN "Dr Sebagh"
    WHEN REGEXP_MATCH(Product Name,'^Elemis.*') THEN "Elemis"
    WHEN REGEXP_MATCH(Product Name,'^Croma.*') THEN "Croma"
    WHEN REGEXP_MATCH(Product Name,'^Exuviance.*') THEN "Exuviance"
    WHEN REGEXP_MATCH(Product Name,'^Kelo-cote.*') THEN "Kelo-cote"
    WHEN REGEXP_MATCH(Product Name,'^Jan Marini.*') THEN "Jan Marini"
END