CASE
WHEN REGEXP_MATCH(RAW-brand,'(?i)VIVIENNE WESTWOOD.*') THEN "VIVIENNE WESTWOOD"
WHEN REGEXP_MATCH(RAW-brand,'(?i)VERSACE.*') THEN "VERSACE"
WHEN REGEXP_MATCH(RAW-brand,'(?i)TOMMY HILFIGER.*') THEN "TOMMY HILFIGER"
WHEN REGEXP_MATCH(RAW-brand,'(?i)STONE ISLAND.*') THEN "STONE ISLAND"
WHEN REGEXP_MATCH(RAW-brand,'(?i)STELLA MCCARTNEY.*') THEN "STELLA MCCARTNEY"
WHEN REGEXP_MATCH(RAW-brand,'(?i)SAINT LAURENT.*') THEN "SAINT LAURENT"
WHEN REGEXP_MATCH(RAW-brand,'(?i)PINKO.*') THEN "PINKO"
WHEN REGEXP_MATCH(RAW-brand,'(?i)GUCCI.*') THEN "GUCCI"
WHEN REGEXP_MATCH(RAW-brand,'(?i)ADIDAS.*') THEN "ADIDAS"
WHEN REGEXP_MATCH(RAW-brand,'(?i)GOLDEN GOOSE.*') THEN "GOLDEN GOOSE"
WHEN REGEXP_MATCH(RAW-brand,'(?i)MOSCHINO.*') THEN "MOSCHINO"
WHEN REGEXP_MATCH(RAW-brand,'(?i)MONCLER.*') THEN "MONCLER"
WHEN REGEXP_MATCH(RAW-brand,'(?i)BURBERRY.*') THEN "BURBERRY"
WHEN REGEXP_MATCH(RAW-brand,'(?i)GIVENCHY.*') THEN "GIVENCHY"
WHEN REGEXP_MATCH(RAW-brand,'(?i)NEIL BARRETT.*') THEN "NEIL BARRETT"
ELSE RAW-brand
END
