CASE
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Jellycat.*') THEN "Jellycat"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Harrods.*') THEN "Harrods"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Fresh.*') THEN "Fresh"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Suqqu.*') THEN "Suqqu"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Gucci.*') THEN "Gucci"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Burberry.*') THEN "Burberry"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Armani.*') THEN "Armani"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Canada Goose.*') THEN "Canada Goose"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)MAC.*') THEN "MAC"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)La Mer.*') THEN "La Mer"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Cl&#xE9; de Peau Beaut&#xE9;.*|(?i)Clé de Peau Beauté') THEN "Clé de Peau Beauté"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)YSL.*') THEN "YSL"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Givenchy.*') THEN "Givenchy"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Estée Lauder.*') THEN "Estée Lauder"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Charlotte Tilbury.*') THEN "Charlotte Tilbury"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Guerlain.*') THEN "Guerlain"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)TOM FORD.*') THEN "TOM FORD"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Diptyque.*') THEN "Diptyque"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Maje.*') THEN "Maje"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Huda Beauty.*') THEN "Huda Beauty"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Byredo.*') THEN "Byredo"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Lanc&#xF4;me.*') THEN "Lancôme"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Shiseido.*') THEN "Shiseido"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Acne Studios.*') THEN "Acne Studios"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Hermès.*') THEN "Hermès"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Off-White.*') THEN "Off-White"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)DIOR.*') THEN "DIOR"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Decorté.*') THEN "Decorté"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Loewe.*') THEN "Loewe"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)La Prairie.*') THEN "La Prairie"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Helena Rubinstein.*') THEN "Helena Rubinstein"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Moncler.*') THEN "Moncler"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Decort&#xE9;') THEN "Decorté"
END