CASE

# Fashion Brands
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)canada.*goose.*') THEN "Canada Goose"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)7 For All Mankind.*') THEN "7 For All Mankind"
WHEN RAW-Brand = "A.P.C." THEN "A.P.C."
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)ACNE.*') THEN "Acne Studios"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)adidas.*') THEN "adidas"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Adrianna.*') THEN "Adrianna Papell"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)AGOLDE.*') THEN "AGOLDE"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)Alexander McQueen.*|^(?i)') THEN "Alexander McQueen"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Alexander Wang.*') THEN "Alexander Wang"
WHEN RAW-Brand = "Alice + Olivia" THEN "Alice + Olivia"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Alpha Industries.*') THEN "Alpha Industries"
WHEN REGEXP_MATCH(RAW-Brand,'^AMI.*') THEN "AMI"
WHEN REGEXP_MATCH(RAW-Brand,'^Amiri.*') THEN "Amiri"
WHEN RAW-Brand = "Anderson’s" THEN "Anderson’s"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)ANNI LU.*') THEN "ANNI LU"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)APM Monaco.*') THEN "APM Monaco"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)APPLES & FIGS.*') THEN "APPLES & FIGS"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)AQUAZZURA.*') THEN "AQUAZZURA"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Aspinal of London.*') THEN "Aspinal of London"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Balenciaga.*') THEN "Balenciaga"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Balmain.*') THEN "Balmain"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)BAO BAO ISSEY MIYAKE.*') THEN "BAO BAO ISSEY MIYAKE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Baublebar.*') THEN "Baublebar"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Billionaire Boys Club.*') THEN "Billionaire Boys Club"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Bobbies.*') THEN "Bobbies"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)BOSS.*') THEN "BOSS"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Boyy.*') THEN "Boyy"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Burberry.*') THEN "Burberry"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)BY FAR.*') THEN "BY FAR"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Calvin Klein.*') THEN "Calvin Klein"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Carhartt WIP.*') THEN "Carhartt WIP"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Chloé.*') THEN "Chloé"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Coach.*') THEN "Coach"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Comme des Garçons.*') THEN "Comme des Garçons"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Converse.*') THEN "Converse"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Dior') AND Product Type = "Fashion" THEN "Dior Fashion"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Dr Martens.*') THEN "Dr Martens"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)ELLEME.*') THEN "ELLEME"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Emporio Armani.*') THEN "Emporio Armani"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Evisu.*') THEN "Evisu"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Falke.*') THEN "Falke"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Fendi.*') THEN "Fendi"
WHEN RAW-Brand = "FOR ART'S SAKE" THEN "FOR ART'S SAKE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Frame.*') THEN "Frame"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Free People.*') THEN "Free People"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Gianvito Rossi.*') THEN "Gianvito Rossi"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Gimaguas.*') THEN "Gimaguas"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Givenchy.*') THEN "Givenchy"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Golden Goose.*') THEN "Golden Goose"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Gucci.*') THEN "Gucci"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Heron Preston.*') THEN "Heron Preston"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Isabel Marant Étoile.*') THEN "Isabel Marant Étoile"
WHEN RAW-Brand = "Ivy & Oak" THEN "Ivy & Oak"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)J Brand.*') THEN "J Brand"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Jacquemus.*') THEN "Jacquemus"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Jigsaw.*') THEN "Jigsaw"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Jil Sander.*') THEN "Jil Sander"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Jimmy Choo.*') THEN "Jimmy Choo"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Johnstons of Elgin.*') THEN "Johnstons of Elgin"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)JW Anderson.*') THEN "JW Anderson"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)KEEPSAKE.*') THEN "KEEPSAKE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)KENZO.*') THEN "KENZO"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)LOEWE.*') THEN "LOEWE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Louis Vuitton.*') THEN "Louis Vuitton"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Maison Labiche.*') THEN "Maison Labiche"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Maison Margiela.*') THEN "Maison Margiela"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Malone Souliers.*') THEN "Malone Souliers"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Manolo Blahnik.*') THEN "Manolo Blahnik"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Marc Jacobs') AND Product Type = "Fashion" THEN "Marc Jacobs Fashion"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Marni.*') THEN "Marni"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)MeMe London.*') THEN "MeMe London"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)Michael Kors.*') THEN "Michael Kors"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Miista.*') THEN "Miista"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Missoma.*') THEN "Missoma"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Miu Miu.*') THEN "Miu Miu"
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)Moncler.*') THEN "Moncler"
WHEN RAW-Brand = "Needle & Thread" THEN "Needle & Thread"
WHEN RAW-Brand = "Off-White" THEN "Off-White"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Olivia Burton.*') THEN "Olivia Burton"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Olivia von Halle.*') THEN "Olivia von Halle"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Oneteaspoon.*') THEN "Oneteaspoon"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Palm Angels.*') THEN "Palm Angels"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Paul Smith.*') THEN "Paul Smith"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Polo Ralph Lauren.*') THEN "Polo Ralph Lauren"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Prada.*') THEN "Prada"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Puma.*') THEN "Puma"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Rains.*') THEN "Rains"
WHEN RAW-Brand = "Ray-Ban" THEN "Ray-Ban"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Rimowa.*') THEN "Rimowa"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Saint Laurent.*') THEN "Saint Laurent"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Salondeju.*') THEN "Salondeju"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Salvatore Ferragamo.*') THEN "Salvatore Ferragamo"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Sarah Chapman.*') THEN "Sarah Chapman"
WHEN RAW-Brand = "Self-Portrait" THEN "Self-Portrait"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Sophia Webster.*') THEN "Sophia Webster"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Stand Studio.*') THEN "Stand Studio"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)STAUD.*') THEN "STAUD"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Stella McCartney.*') THEN "Stella McCartney"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Stone Island.*') THEN "Stone Island"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Thom Browne.*') THEN "Thom Browne"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Tory Burch.*') THEN "Tory Burch"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)True Decadence.*') THEN "True Decadence"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Valentino.*') THEN "Valentino"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Veja.*') THEN "Veja"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Versace.*') THEN "Versace"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Vince.*') THEN "Vince"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Vivienne Westwood.*') THEN "Vivienne Westwood"
WHEN RAW-Brand = "Y-3" THEN "Y-3"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Yuul Yie.*') THEN "Yuul Yie"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Zimmermann.*') THEN "Zimmermann"

# Beauty Brand
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)111SKIN.*') THEN "111SKIN"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Acqua di Parma.*') THEN "Acqua di Parma"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Anastasia Beverly Hills.*') THEN "Anastasia Beverly Hills"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Anatomicals.*') THEN "Anatomicals"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Armani.*Beauty.*') THEN "Armani Beauty"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Atelier Cologne.*') THEN "Atelier Cologne"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)AUGUSTINUS BADER.*') THEN "AUGUSTINUS BADER"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Aveda.*') THEN "Aveda"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)beautyblender.*') THEN "beautyblender"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Benefit.*') THEN "Benefit"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)BVLGARI.*') THEN "BVLGARI"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)C TILBURY.*') THEN "C TILBURY"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)CAUDALIE.*') THEN "CAUDALIE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)CHANEL.*') THEN "CHANEL"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)CHANTECAILLE.*') THEN "CHANTECAILLE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Charlotte.*Tilbury.*') THEN "Charlotte Tilbury"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Cover FX.*') THEN "Cover FX"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Creed.*') THEN "Creed"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)CREME DLM.*') THEN "CREME DLM"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Dermalogica.*') THEN "Dermalogica"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Dior') AND Product Type = "Beauty" THEN "Dior Beauty"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Elemis.*') THEN "Elemis"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)ESPA.*') THEN "ESPA"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Estée Lauder.*') THEN "Estée Lauder"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Eve.*Lom.*') THEN "Eve Lom"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Ex Nihilo.*') THEN "Ex Nihilo"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)FENTY.*') THEN "FENTY"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)FOREO.*') THEN "FOREO"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)ghd.*') THEN "ghd"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)HERMÈS.*') THEN "HERMÈS"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)HOURGLASS.*') THEN "HOURGLASS"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)HUDA BEAUTY.*') THEN "HUDA BEAUTY"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)JINMEE.*') THEN "JINMEE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Jo Malone.*') THEN "Jo Malone"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Juliette Has a Gun.*') THEN "Juliette Has a Gun"
WHEN RAW-Brand = "Kiehl's" THEN "Kiehl's"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Kilian.*') THEN "Kilian"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)La Mer.*') THEN "La Mer"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)La Prairie.*') THEN "La Prairie"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Lancôme.*') THEN "Lancôme"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)LAPRAIRIE.*') THEN "LAPRAIRIE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Laura Mercier.*') THEN "Laura Mercier"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Le.*Labo.*') THEN "Le Labo"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)MAC.*') THEN "MAC"
WHEN REGEXP_MATCH(RAW-Brand,'(?i)Marc Jacobs') AND Product Type = "Beauty" THEN "Marc Jacobs Beauty"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Mario Badescu.*') THEN "Mario Badescu"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Marvis.*') THEN "Marvis"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Merci Handy.*') THEN "Merci Handy"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)NARS.*') THEN "NARS"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)OUAI.*') THEN "OUAI"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)PHILOSOPHY.*') THEN "PHILOSOPHY"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Pixi.*') THEN "Pixi"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)REGENERATE.*') THEN "REGENERATE"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)RéVive.*|^(?i)REVIVE$') THEN "RéVive"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Rodial.*') THEN "Rodial"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Serge Lutens.*') THEN "Serge Lutens"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)SHISEIDO.*') THEN "SHISEIDO"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Sisley.*') THEN "Sisley"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Skin Chemists.*') THEN "Skin Chemists"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Stila.*') THEN "Stila"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)THE ORDINA.*') THEN "THE ORDINA"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)THE ORDINARY.*') THEN "THE ORDINARY"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)This Works.*') THEN "This Works"
WHEN RAW-Brand = "Tiffany & Co." THEN "Tiffany & Co."
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Tom.*Ford.*') THEN "Tom Ford"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Urban Decay.*') THEN "Urban Decay"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)VALMONT.*') THEN "VALMONT"
WHEN REGEXP_MATCH(RAW-Brand,'^(?i)Yves Saint Laurent.*') THEN "YSL"

#Food
WHEN REGEXP_MATCH(RAW-Brand,'.*(?i)Manuka Honey.*') THEN "Manuka Honey"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Alfieri.*') THEN "Alfieri"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Booja Booja.*') THEN "Booja Booja"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Butlers Chocolates.*') THEN "Butlers Chocolates"
WHEN RAW-Brand = "Cartwright & Butler" THEN "Cartwright & Butler"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Charbonnel Et Walker.*') THEN "Charbonnel Et Walker"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Choconchoc.*') THEN "Choconchoc"
WHEN RAW-Brand = "Coca-Cola" THEN "Coca-Cola"
WHEN RAW-Brand = "Flower & White" THEN "Flower & White"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Glico.*') THEN "Glico"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Godiva.*') THEN "Godiva"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Harvey Nichols.*') THEN "Harvey Nichols"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Jealous Sweets.*') THEN "Jealous Sweets"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Marutai.*') THEN "Marutai"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Meiji.*') THEN "Meiji"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)OTHER FOODS CHIPS.*') THEN "OTHER FOODS CHIPS"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Ototo.*') THEN "Ototo"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Quaranta.*') THEN "Quaranta"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Rococo.*') THEN "Rococo"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Tiptree.*') THEN "Tiptree"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Torres.*') THEN "Torres"
WHEN REGEXP_MATCH(RAW-Brand,'.^(?i)Walkers Shortbread.*') THEN "Walkers Shortbread"

END