CASE
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)holland.*barrett.*') THEN "Holland & Barrett"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)bootea.*') THEN "Bootea"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)manuka pharm.*') THEN "Manuka Pharm"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)zera.*') THEN "Zera"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)yutaka.*') THEN "Yutaka"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)yushoi.*') THEN "Yushoi"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)yumi.*') THEN "Yumi"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)yourzooki.*') THEN "YourZooki"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)yogi tea.*') THEN "Yogi Tea"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)yes wb.*') THEN "YES WB"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)xls.*') THEN "XLS"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)women.*s best.*') THEN "Women's Best"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)willy.*s.*') THEN "Willy's"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)whole earth.*') THEN "Whole Earth"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)whites oat bran.*') THEN "Whites Oat Bran"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)what a melon.*') THEN "What A Melon"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)whamisa.*') THEN "Whamisa"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)westlab.*') THEN "Westlab"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)Western.*') THEN "Western"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)weleda.*') THEN "Weleda"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)volvic.*') THEN "Volvic"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)viviscal.*') THEN "Viviscal"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)vivid.*') THEN "Vivid"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)Vitness.*') THEN "Vitness"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)vitaskin.*') THEN "Vitaskin"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)vitaboost.*') THEN "VitaBoost"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)vitabiotics.*') THEN "Vitabiotics"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)vita coco.*') THEN "Vita Coco"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)virusol.*') THEN "Virusol"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)usn.*') THEN "USN"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)urban veda.*') THEN "Urban Veda"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)unbeelievable.*') THEN "Unbeelievable"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)ufit.*') THEN "uFIT"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)twinings.*') THEN "Twinings"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)trilogy.*') THEN "Trilogy"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)trek.*') THEN "Trek"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)tree of life.*') THEN "Tree Of Life"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)tisserand.*') THEN "Tisserand"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)thrive.*') THEN "Thrive"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)The Vital Ingredient.*') THEN "The Vital Ingredient"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)the skinny food co.*') THEN "The Skinny Food Co"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)the raw chocolate company.*') THEN "The Raw Chocolate Co"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)the jojoba company.*') THEN "The Jojoba Company"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)the humble.*') THEN "The Humble"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)the groovy food.*') THEN "Groovy Food"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)the berry company.*') THEN "the Berry"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)total sweet.*') THEN "Total Sweet"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)the beginnings.*') THEN "The Beginnings"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)ten acre.*') THEN "Ten Acre"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)tea pigs.*') THEN "Tea Pigs"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sweet freedom.*') THEN "Sweet Freedom"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sunsweet.*') THEN "Sunsweet"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sunita.*') THEN "Sunita"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sula.*') THEN "Sula"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sukin.*') THEN "Sukin"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sterimar.*') THEN "Sterimar"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)starpowa.*') THEN "Starpowa"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)Sowan.*') THEN "Sowan's"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)Source.*') THEN "Source"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)solgar.*') THEN "Solgar"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)so free.*') THEN "So Free"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)skinny coffee club.*') THEN "Skinny Coffee Club"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)skin academy.*') THEN "Skin Academy"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)seedful.*') THEN "Seedful"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sea magik.*') THEN "Sea Magik"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)scrub love.*') THEN "Scrub Love"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sannol.*') THEN "Sannol"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)san pellegrino.*') THEN "S.Pellegrino"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)sambucol.*') THEN "Sambucol"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)salt of the earth.*') THEN "Salt Of The Earth"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)rude health.*') THEN "Rude Health"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)rowse.*') THEN "Rowse"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)roastworks.*') THEN "Roastworks"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)ricola.*') THEN "Ricola"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)remedy.*') THEN "Remedy"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)raw bean.*') THEN "RawBean"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)quinola.*') THEN "QUINOLA"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)quest.*') THEN "QUEST"
    WHEN REGEXP_MATCH(meta_item_item_name,'(?i)puressentiel.*') THEN "Puressentiel"

    -- pure gold select npa manuka honey 5
END