CASE
    WHEN Product Brand IN ('Abercrombie and Fitch','Acqua Di Parma','Andrew Collinge','Anna Sui','Atelier Cologne','Aveda','Balenciaga','Bare Minerals','Barry M','Baxter of California','Baylis and Harding','Benefit','Bobbi Brown','Bottega Veneta','Bronnley','Cartier','Charlotte Tilbury','Chloe','Clarins','Clinique','Cover FX Skin Care','Creed','Darphin','Davidoff','Dior','Dolce and Gabbana','Dunhill','E.Coudray','Elemis','Elie Saab','Elizabeth And James','Elizabeth Arden','Erborian','Estee Lauder','Ferrari','Filorga','Folklore','Frederic Malle','GHD','GIVENCHY','Gentlemens Hardware','Giorgio Armani','Glamglow','Goutal','Grace Cole','Gucci','Guerlain','HAWKINS AND BRIMBLE','Hermes','House of Fraser','Issey Miyake','Jack Black','Jimmy Choo','Jo Malone','Juicy Couture','Kiehls','Kilian','Konjac Sponges','L Occitane','La Mer','La Prairie','Lab Series','Lancome','Laura Geller','Laura Mercier','Mac','Marc Jacobs','Mens Rock','Miu Miu','Molton Brown','Mr Natty','Mugler','Mugler Alien','Murad','Narciso Rodriguez','Nars','Niod','Olfactive Studio','Origins','Pixi','Profusion Cosmetics','Ren','Roger and Gallet','Serge Lutens','Shiseido','Sisley','SportFX','Stila','Tangle Teezer','The Ordinary','Tiffany','Tom Ford','Tony Moly','Triumph and Disaster','Ultra Sun','Urban Decay','Van Cleef and Arpels','Viktor & Rolf','YSL') OR REGEXP_MATCH(Product Name,'.*Eau de.*')
        THEN "Beauty"
    
    WHEN Product Brand IN ('adidas','Adrianna Papell','Agent Provocateur','Aldo','Alexandre','Alpha Industries','American Tourister','Asics','BOSS','Barbour','Bardot','Bertie','Biba','Boss','Boutique Bowls','Burberry','Bvlgari','Calvin Klein','Carvela','Champion','Character','Charnos','Coach','Colourworks','Converse','Criminal','Cyberjammies','DKNY','Decleor','Diesel','Dune London','Eastpak','Eliza J','Emporio Armani','Everlast','Fashion Union','Feud','Firetrap','Folli Follie','French Connection','Furla','Gelert','Ginia','Guess','Hampton','Herschel','Howick','Jack Wills','Jack and Jones','Jeffrey Campbell','Joules','KG Kurt Geiger','Kangol','Karen Millen','Karl Lagerfeld','Karrimor','Kate Spade New York','Kenzo','Kurt Geiger London','L Agent by Agent Provocateur','Lacoste','Label Lab','Levis','Links of London','Longchamp','Lonsdale','Moschino','MCM','Maison De Nimes','Maison Margiela Paris','Mario Valentino','Marvel','Mason Knight Yager','Max Mara','Mela','Michael Kors','Mint Velvet','Miss KG','Miss Selfridge','Nine West','Noisy May','Nougat','Oasis','Odlo','Olivia Burton','Original Penguin','Paul Smith','Pierre Cardin','Puma','RFU','Radley','Raging Bull','Ralph Lauren','Reebok','Regatta','Shock Absorber','Sidewalk Sport','Sistaglam','Skopes','Slazenger','Sloggi','SoulCal','Star Wars','Story of Lola','Superdry','Swarovski','Ted Baker','The North Face','Therapy London','Three Floor','Tommy Bodywear','Tommy Hilfiger','Tommy Jeans','Tory Burch','Totes','Triumph','USA Pro','Ugg','Under Armour','Vivienne Westwood','Warehouse','Whistles','Wolford','Wrangler')
        THEN "Fashion"

    WHEN Product Brand IN ('Carlton','Cartwright and Butler','Chase and Wonder','Christy','Daewoo','Dyson','Ecoya','Edinburgh Preserves','Gray and Willow','Green Pan','Hotel Collection','Joe and Sephs','Joseph Joseph','Junipa','Just Sheepskin','Kitchen Pantry','LEGO','LSA','Le Creuset','Linea','M.Y','NPW','No Fear','Paperchase','Pretty Useful Tools','Samsonite','Sanderson','Sara Miller','Sophie Conran for Portmeirion','Tefal','Typhoon','Yoga Mad')
        THEN "Homeware"

    WHEN Product Brand IN ('Charbonnel et Walker')
        THEN "Food"
END
