CASE
  WHEN REGEXP_MATCH(Product Name, 'Estee Lauder.*') THEN "Estée Lauder"
  WHEN REGEXP_MATCH(Product Name, 'Lancôme.*|Lancome.*') THEN "Lancôme"
  WHEN REGEXP_MATCH(Product Name, 'NARS.*') THEN "NARS"
  WHEN REGEXP_MATCH(Product Name, 'Regenerate.*') THEN "Regenerate"
  WHEN REGEXP_MATCH(Product Name, 'Giorgio Armani.*|(?i)Armani.*') THEN "Giorgio Armani"
  WHEN REGEXP_MATCH(Product Name, 'Origins.*') THEN "Origins"
  WHEN REGEXP_MATCH(Product Name, 'Caudalie.*') THEN "Caudalie"
  WHEN REGEXP_MATCH(Product Name, 'Clinique.*') THEN "Clinique"
  WHEN REGEXP_MATCH(Product Name, 'The Ordinary.*') THEN "The Ordinary"
  WHEN REGEXP_MATCH(Product Name, 'Rituals.*') THEN "Rituals"
  WHEN REGEXP_MATCH(Product Name, 'Christophe Robin.*') THEN "Christophe Robin"
  WHEN REGEXP_MATCH(Product Name, 'Filorga.*') THEN "Filorga"
  WHEN REGEXP_MATCH(Product Name, 'Lab.*Series.*') THEN "LabSeries"
  WHEN REGEXP_MATCH(Product Name, 'Tangle Teezer.*') THEN "Tangle Teezer"
  WHEN REGEXP_MATCH(Product Name, 'Yves Saint Laurent.*|YSL.*') THEN "YSL"
  WHEN REGEXP_MATCH(Product Name, 'Erno Laszlo.*') THEN "Erno Laszlo"
  WHEN REGEXP_MATCH(Product Name, 'CeraVe.*') THEN "CeraVe"
  WHEN REGEXP_MATCH(Product Name, 'Philip.*') THEN "Philip"
  WHEN REGEXP_MATCH(Product Name, 'NYX.*') THEN "NYX"
  WHEN REGEXP_MATCH(Product Name, 'Grow Gorgeous.*') THEN "Grow Gorgeous"
  WHEN REGEXP_MATCH(Product Name, 'Bobbi Brown.*') THEN "Bobbi Brown"
  WHEN REGEXP_MATCH(Product Name, 'Kerastase.*|Kérastase.*') THEN "Kérastase"
  WHEN REGEXP_MATCH(Product Name, 'La Roche-Posay.*') THEN "La Roche-Posay"
  WHEN REGEXP_MATCH(Product Name, '(?i)PIXI.*') THEN "PIXI"
  WHEN REGEXP_MATCH(Product Name, 'Elizabeth Arden.*') THEN "Elizabeth Arden"
  WHEN REGEXP_MATCH(Product Name, 'Eve Lom.*') THEN "Eve Lom"
  WHEN REGEXP_MATCH(Product Name, 'Shiseido.*') THEN "Shiseido"
  WHEN REGEXP_MATCH(Product Name, 'Urban Decay.*') THEN "Urban Decay"
  WHEN REGEXP_MATCH(Product Name, 'Illamasqua.*') THEN "Illamasqua"
  WHEN REGEXP_MATCH(Product Name, 'Molton Brown.*') THEN "Molton Brown"
  WHEN REGEXP_MATCH(Product Name, 'MAC.*|M·A·C.*') THEN "MAC"
  WHEN REGEXP_MATCH(Product Name, 'Burberry.*') THEN "Burberry"
  WHEN REGEXP_MATCH(Product Name, '(?i)FARMACY.*') THEN "FARMACY"
  WHEN REGEXP_MATCH(Product Name, 'L’Oreal.*|L&#039;Oreal.*') THEN "L’Oreal"
  WHEN REGEXP_MATCH(Product Name, 'Bumble and bumble.*') THEN "Bumble and bumble"
  WHEN REGEXP_MATCH(Product Name, 'Aesop.*') THEN "Aesop"
  WHEN REGEXP_MATCH(Product Name, 'First (?i)Aid.*') THEN "First Aid"
  WHEN REGEXP_MATCH(Product Name, 'Hair.*burst.*') THEN "Hairburst"
  WHEN REGEXP_MATCH(Product Name, '(?i)NuFACE.*') THEN "NuFACE"
  WHEN REGEXP_MATCH(Product Name, '(?i)DECLÉOR.*') THEN "DECLÉOR"
  WHEN REGEXP_MATCH(Product Name, '(?i)Dr.Jart.*') THEN "Dr.Jart+"
  WHEN REGEXP_MATCH(Product Name, '(?i)Avène.*|(?i)Avene.*') THEN "Avène"
  WHEN REGEXP_MATCH(Product Name, '(?i)Ultrasun.*') THEN "Ultrasun"
  WHEN REGEXP_MATCH(Product Name, '(?i)Real Techniques.*') THEN "Real Techniques"
  WHEN REGEXP_MATCH(Product Name, '(?i)Chantecaille.*') THEN "Chantecaille"
  WHEN REGEXP_MATCH(Product Name, '(?i)COSRX.*') THEN "COSRX"
  WHEN REGEXP_MATCH(Product Name, '(?i).*Marvis.*') THEN "Marvis"
  WHEN REGEXP_MATCH(Product Name, '(?i)Laura Mercier.*') THEN "Laura Mercier"
  WHEN REGEXP_MATCH(Product Name, '(?i)TONYMOLY.*') THEN "TONYMOLY"
  WHEN REGEXP_MATCH(Product Name, '(?i)Vichy.*') THEN "Vichy"
  WHEN REGEXP_MATCH(Product Name, '(?i)The Jojoba.*') THEN "The Jojoba Company"
  WHEN REGEXP_MATCH(Product Name, '(?i)Dermalogica.*') THEN "Dermalogica"
  WHEN REGEXP_MATCH(Product Name, '(?i)this works.*') THEN "this works"
  WHEN REGEXP_MATCH(Product Name, '(?i)Eyeko.*') THEN "Eyeko"
  WHEN REGEXP_MATCH(Product Name, '(?i)By Terry.*') THEN "By Terry"
  WHEN REGEXP_MATCH(Product Name, '(?i)L:A BRUKET.*') THEN "L:A Bruket"
  WHEN REGEXP_MATCH(Product Name, '(?i)OUAI.*') THEN "OUAI"
  WHEN REGEXP_MATCH(Product Name, '(?i)Embryolisse.*') THEN "Embryolisse"
  WHEN REGEXP_MATCH(Product Name, '(?i)Garnier.*') THEN "Garnier"
  WHEN REGEXP_MATCH(Product Name, '(?i)Redken.*') THEN "Redken"
  WHEN REGEXP_MATCH(Product Name, '(?i)Stila.*') THEN "Stila"
  WHEN REGEXP_MATCH(Product Name, '(?i)Rodial.*') THEN "Rodial"
  WHEN REGEXP_MATCH(Product Name, '(?i)KORRES.*') THEN "KORRES"
  WHEN REGEXP_MATCH(Product Name, '(?i)bareMinerals.*') THEN "bareMinerals"
  WHEN REGEXP_MATCH(Product Name, '(?i)ALGENIST.*') THEN "ALGENIST"
  WHEN REGEXP_MATCH(Product Name, '(?i)Holika Holika.*') THEN "Holika Holika"
  WHEN REGEXP_MATCH(Product Name, '(?i)Aveda.*') THEN "Aveda"
  WHEN REGEXP_MATCH(Product Name, '(?i)essie.*') THEN "essie"
  WHEN REGEXP_MATCH(Product Name, '(?i)Burt&#039;s Bees.*|(?i)Burt.*s Bees.*') THEN "Burt's Bees"
  WHEN REGEXP_MATCH(Product Name, '(?i)Living Proof.*') THEN "Living Proof"
  WHEN REGEXP_MATCH(Product Name, '(?i)Sigma.*') THEN "Sigma"
  WHEN REGEXP_MATCH(Product Name, '(?i)DHC.*') THEN "DHC"
  WHEN REGEXP_MATCH(Product Name, '(?i)GLAMGLOW.*') THEN "GLAMGLOW"
  WHEN REGEXP_MATCH(Product Name, '(?i)Neal&#039;s Yard.*|(?i)Neal.*s Yard.*') THEN "Neal's Yard"
  WHEN REGEXP_MATCH(Product Name, '(?i)philosophy.*') THEN "philosophy"
  WHEN REGEXP_MATCH(Product Name, 'REN .*') THEN "REN"
  WHEN REGEXP_MATCH(Product Name, '(?i)Elemis.*') THEN "Elemis"
  WHEN REGEXP_MATCH(Product Name, '(?i)Jo Malone.*') THEN "Jo Malone"
  WHEN REGEXP_MATCH(Product Name, '(?i)Jurlique.*') THEN "Jurlique"
  WHEN REGEXP_MATCH(Product Name, '(?i)FOREO.*') THEN "FOREO"
  WHEN REGEXP_MATCH(Product Name, '(?i)Darphin.*') THEN "Darphin"
  WHEN REGEXP_MATCH(Product Name, '(?i)benefit.*') THEN "benefit"
  WHEN REGEXP_MATCH(Product Name, '(?i)Bioderma.*') THEN "Bioderma"
  WHEN REGEXP_MATCH(Product Name, '(?i)NUXE.*') THEN "NUXE"
  WHEN REGEXP_MATCH(Product Name, '(?i)SkinCeuticals.*') THEN "SkinCeuticals"
  WHEN REGEXP_MATCH(Product Name, '(?i)Too Faced.*') THEN "Too Faced"
  WHEN REGEXP_MATCH(Product Name, '(?i)Moroccan.*oil.*') THEN "Moroccanoil"
  WHEN REGEXP_MATCH(Product Name, '(?i)Decorte.*|(?i)Decorté.*') THEN "Decorté"
  WHEN REGEXP_MATCH(Product Name, '(?i)NEOM.*') THEN "NEOM"
  WHEN REGEXP_MATCH(Product Name, '(?i)RMK.*') THEN "RMK"
  WHEN REGEXP_MATCH(Product Name, '(?i)freezeframe.*') THEN "freezeframe"
  WHEN REGEXP_MATCH(Product Name, '(?i)Sarah Chapman.*') THEN "Sarah Chapman"
  WHEN REGEXP_MATCH(Product Name, '(?i)Antipodes.*') THEN "Antipodes"
  WHEN REGEXP_MATCH(Product Name, '(?i)Bean Body.*') THEN "Bean Body"
  WHEN REGEXP_MATCH(Product Name, '(?i)Vita Liberata.*') THEN "Vita Liberata"
  WHEN REGEXP_MATCH(Product Name, '(?i)Bloom and Blossom.*') THEN "Bloom and Blossom"
  WHEN REGEXP_MATCH(Product Name, '(?i)Uriage.*') THEN "URIAGE"
  WHEN REGEXP_MATCH(Product Name, '(?i)BIOEFFECT.*') THEN "BIOEFFECT"
  WHEN REGEXP_MATCH(Product Name, '(?i)wet n wild.*') THEN "Wet n Wild"
  WHEN REGEXP_MATCH(Product Name, '(?i)Omorovicza.*') THEN "Omorovicza"
  WHEN REGEXP_MATCH(Product Name, '(?i)Alpecin.*') THEN "Alpecin"
  WHEN REGEXP_MATCH(Product Name, '(?i)Dr. Hauschka.*') THEN "Dr. Hauschka"
  WHEN REGEXP_MATCH(Product Name, 'OPI.*') THEN "OPI"
  WHEN REGEXP_MATCH(Product Name, '(?i)ESPA.*') THEN "ESPA"
  WHEN REGEXP_MATCH(Product Name, '(?i)ghd.*') THEN "ghd"
  WHEN REGEXP_MATCH(Product Name, 'The Ritual.*|Rituals.*') THEN "Rituals"
  WHEN REGEXP_MATCH(Product Name, '(?i)Max Factor.*') THEN "Max Factor"
  WHEN REGEXP_MATCH(Product Name, '(?i)Smashbox.*') THEN "Smashbox"
  WHEN REGEXP_MATCH(Product Name, '(?i)Murad.*') THEN "Murad"
  WHEN REGEXP_MATCH(Product Name, '(?i)Aveeno.*') THEN "Aveeno"
  WHEN REGEXP_MATCH(Product Name, '(?i)AHAVA.*') THEN "AHAVA"
  WHEN REGEXP_MATCH(Product Name, '(?i)Rimmel.*') THEN "RIMMEL"
  WHEN REGEXP_MATCH(Product Name, '(?i)Skin Republic.*') THEN "Skin Republic"
  WHEN REGEXP_MATCH(Product Name, '(?i)KLORANE.*') THEN "KLORANE"
  WHEN REGEXP_MATCH(Product Name, '(?i)NIOD.*') THEN "NIOD"
  WHEN REGEXP_MATCH(Product Name, '(?i)BeautyPro.*') THEN "BeautyPro"
  WHEN REGEXP_MATCH(Product Name, '(?i)Magnitone.*') THEN "Magnitone"
  WHEN REGEXP_MATCH(Product Name, '(?i)Barry M .*') THEN "Barry M"
  WHEN REGEXP_MATCH(Product Name, '(?i)pupa.*') THEN "Pupa"
  WHEN REGEXP_MATCH(Product Name, '(?i)Aquis.*') THEN "Aquis"
  WHEN REGEXP_MATCH(Product Name, '(?i)AMELIORATE.*') THEN "AMELIORATE"
  WHEN REGEXP_MATCH(Product Name, '(?i)Lumene.*') THEN "Lumene"
  WHEN REGEXP_MATCH(Product Name, '(?i)Olaplex.*') THEN "Olaplex"
  WHEN REGEXP_MATCH(Product Name, '(?i)peter thomas roth.*') THEN "Peter Thomas Roth"
  WHEN REGEXP_MATCH(Product Name, '(?i)Egyptian Magic.*') THEN "Egyptian Magic"
  WHEN REGEXP_MATCH(Product Name, '(?i)Balmain.*') THEN "Balmain"
  WHEN REGEXP_MATCH(Product Name, '(?i)Zelens.*') THEN "Zelens"
  WHEN REGEXP_MATCH(Product Name, '(?i)Iluminage.*') THEN "Iluminage"
  WHEN REGEXP_MATCH(Product Name, '(?i)APIVITA.*') THEN "APIVITA"
  WHEN REGEXP_MATCH(Product Name, '(?i)JASON.*') THEN "JĀSÖN"
  WHEN REGEXP_MATCH(Product Name, '(?i)Maybelline.*') THEN "Maybelline"
  WHEN REGEXP_MATCH(Product Name, '(?i)Paula&#039;s Choice.*|(?i)Paula.*s Choice.*') THEN "Paula's Choice"
  WHEN REGEXP_MATCH(Product Name, '(?i)natasha.*') THEN "natasha"
  WHEN REGEXP_MATCH(Product Name, '(?i)VERSO.*') THEN "VERSO"
  WHEN REGEXP_MATCH(Product Name, '(?i)Rapid.*Lash.*') THEN "Rapid Lash"
  WHEN REGEXP_MATCH(Product Name, '(?i)Omorovizcza.*') THEN "Omorovizcza"
  WHEN REGEXP_MATCH(Product Name, '(?i)Skimono.*') THEN "Skimono"
  WHEN REGEXP_MATCH(Product Name, '(?i)Manuka Doctor.*') THEN "Manuka Doctor"
  WHEN REGEXP_MATCH(Product Name, '(?i)Dr.*Botanicals.*') THEN "Dr Botanicals"
  WHEN REGEXP_MATCH(Product Name, '(?i)skinChemists.*') THEN "skinChemists"
  WHEN REGEXP_MATCH(Product Name, '(?i)Mama Mio.*') THEN "Mama Mio"
  WHEN REGEXP_MATCH(Product Name, '(?i)Avant Skincare.*') THEN "Avant Skincare"
  WHEN REGEXP_MATCH(Product Name, '(?i)MÁDARA.*') THEN "MÁDARA"
  WHEN REGEXP_MATCH(Product Name, '(?i)StriVectin.*') THEN "StriVectin"
  WHEN REGEXP_MATCH(Product Name, '(?i)Emma Hardie.*') THEN "Emma Hardie"
  WHEN REGEXP_MATCH(Product Name, '(?i)Cover FX.*') THEN "Cover FX"
  WHEN REGEXP_MATCH(Product Name, '(?i)Kevyn Aucoin.*') THEN "Kevyn Aucoin"
  WHEN REGEXP_MATCH(Product Name, '(?i)ARgENTUM.*') THEN "ARgENTUM"
  WHEN REGEXP_MATCH(Product Name, '(?i)STARSKIN.*') THEN "STARSKIN"
  WHEN REGEXP_MATCH(Product Name, '(?i)111SKIN.*') THEN "111SKIN"
  WHEN REGEXP_MATCH(Product Name, '(?i)ZOEVA.*') THEN "ZOEVA"
  WHEN REGEXP_MATCH(Product Name, '(?i)Vita.*') THEN "Vita Liberata"
  WHEN REGEXP_MATCH(Product Name, '(?i)Percy &amp; Reed.*') THEN "Percy & Reed"
  WHEN REGEXP_MATCH(Product Name, '(?i)Imbue Curl.*') THEN "Imbue Curl"
  WHEN REGEXP_MATCH(Product Name, '(?i)Eucerin.*') THEN "Eucerin"
  WHEN REGEXP_MATCH(Product Name, '(?i)TriPollar.*') THEN "TriPollar"
  WHEN REGEXP_MATCH(Product Name, '(?i)INIKA.*') THEN "INIKA"
  WHEN REGEXP_MATCH(Product Name, '(?i)EcoTools.*') THEN "EcoTools"
  WHEN REGEXP_MATCH(Product Name, '(?i)invisibobble.*') THEN "invisibobble"
  WHEN REGEXP_MATCH(Product Name, '(?i)Neutrogena.*') THEN "Neutrogena"
  WHEN REGEXP_MATCH(Product Name, '(?i)brushworks.*') THEN "brushworks"
  WHEN REGEXP_MATCH(Product Name, '(?i)westlab.*') THEN "westlab"
  WHEN REGEXP_MATCH(Product Name, '(?i)Revolution.*') THEN "Revolution"
  WHEN REGEXP_MATCH(Product Name, '(?i)Prada.*') THEN "Prada"
  WHEN REGEXP_MATCH(Product Name, '(?i)Narciso.*') THEN "Narciso"
  WHEN REGEXP_MATCH(Product Name, '(?i)Medik8.*') THEN "Medik8"
  WHEN REGEXP_MATCH(Product Name, '(?i)Sol de Janeiro.*') THEN "Sol de Janeiro"
  WHEN REGEXP_MATCH(Product Name, '(?i)Maui Moisture.*') THEN "Maui Moisture"
  WHEN REGEXP_MATCH(Product Name, 'OGX.*') THEN "OGX"
  WHEN REGEXP_MATCH(Product Name, '(?i)Carrière Frères.*') THEN "Carrière Frères"
  WHEN REGEXP_MATCH(Product Name, '(?i)Tom Ford.*') THEN "Tom Ford"
  WHEN REGEXP_MATCH(Product Name, '(?i)Aussie.*') THEN "Aussie"
  WHEN REGEXP_MATCH(Product Name, '(?i).*LookFantastic.*|LF.*') THEN "LookFantastic"
END
