CASE
	WHEN REGEXP_MATCH(products,'.*"product_name":"in homeware.*') THEN "in homeware"
    WHEN REGEXP_MATCH(products,'.*"product_name":"The North Face.*') THEN "The North Face"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Parajumpers.*') THEN "Parajumpers"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Joseph Joseph.*') THEN "Joseph Joseph"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Monopoly.*') THEN "Monopoly"
    WHEN REGEXP_MATCH(products,'.*"product_name":"MP.*') THEN "MP"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Barbour.*') THEN "Barbour"
    WHEN REGEXP_MATCH(products,'.*"product_name":"BRITA.*') THEN "BRITA"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Timberland.*') THEN "Timberland"
    WHEN REGEXP_MATCH(products,'.*"product_name":"The Cambridge Satchel.*') THEN "The Cambridge Satchel"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Dr. Martens.*') THEN "Dr. Martens"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Furla.*') THEN "Furla"
    WHEN REGEXP_MATCH(products,'.*"product_name":"MICHAEL MICHAEL KORS.*') THEN "MICHAEL KORS"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Le Creuset.*') THEN "Le Creuset"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Staub.*') THEN "Staub"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Ash.*') THEN "Ash"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Pinko.*') THEN "Pinko"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Fjallraven.*') THEN "Fjallraven"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Tommy Hilfiger.*') THEN "Tommy Hilfiger"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Olivia Burton.*') THEN "Olivia Burton"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Levi.*') THEN "Levi's"
    WHEN REGEXP_MATCH(products,'.*"product_name":"UGG.*') THEN "UGG"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Clarks.*') THEN "Clarks"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Calvin Klein.*') THEN "Calvin Klein"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Champion.*') THEN "Champion"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Superdry.*') THEN "Superdry"
    WHEN REGEXP_MATCH(products,'.*"product_name":"Natio.*') THEN "Natio"
END