CASE
WHEN REGEXP_MATCH(Product Name,'(?i)shiseido.*') THEN "Shiseido"
WHEN REGEXP_MATCH(Product Name,'(?i)Anna Sui.*') THEN "Anna Sui"
WHEN REGEXP_MATCH(Product Name,'(?i)Emporio Armani.*') THEN "Armani"
WHEN REGEXP_MATCH(Product Name,'(?i)Bulgari.*') THEN "Bulgari"
WHEN REGEXP_MATCH(Product Name,'(?i)Burberry.*') THEN "Burberry"
WHEN REGEXP_MATCH(Product Name,'(?i)By Terry.*') THEN "By Terry"
WHEN REGEXP_MATCH(Product Name,'(?i)Calvin Klein.*') THEN "Calvin Klein"
WHEN REGEXP_MATCH(Product Name,'(?i)Chanel.*') THEN "Chanel"
WHEN REGEXP_MATCH(Product Name,'(?i)Chloe.*') THEN "Chloe"
WHEN REGEXP_MATCH(Product Name,'(?i)Christophe Robin.*') THEN "Christophe Robin"
WHEN REGEXP_MATCH(Product Name,'(?i)Clarins.*') THEN "Clarins"
WHEN REGEXP_MATCH(Product Name,'(?i)Clarisonic.*') THEN "Clarisonic"
WHEN REGEXP_MATCH(Product Name,'(?i)Clinique.*') THEN "Clinique"
WHEN REGEXP_MATCH(Product Name,'(?i)Coach.*') THEN "Coach"
WHEN REGEXP_MATCH(Product Name,'(?i)Dior.*') THEN "Dior"
WHEN REGEXP_MATCH(Product Name,'(?i)Dolce.*Gabbana.*') THEN "Dolce & Gabbana"
WHEN REGEXP_MATCH(Product Name,'(?i)Elizabeth Arden.*') THEN "Elizabeth Arden"
WHEN REGEXP_MATCH(Product Name,'(?i)Erno Laszlo.*') THEN "Erno Laszlo"
WHEN REGEXP_MATCH(Product Name,'(?i)Estée Lauder.*|(?i)estee lauder.*') THEN "Estée Lauder"
WHEN REGEXP_MATCH(Product Name,'(?i)Eve Lom.*') THEN "Eve Lom"
WHEN REGEXP_MATCH(Product Name,'(?i)Filorga.*') THEN "Filorga"
WHEN REGEXP_MATCH(Product Name,'(?i)GlamGlow.*') THEN "GlamGlow"
WHEN REGEXP_MATCH(Product Name,'(?i)Gucci.*') THEN "Gucci"
WHEN REGEXP_MATCH(Product Name,'(?i)Guerlain.*') THEN "Guerlain"
WHEN REGEXP_MATCH(Product Name,'(?i)Gweniss.*') THEN "Gweniss"
WHEN REGEXP_MATCH(Product Name,'(?i)Hermès.*') THEN "Hermès"
WHEN REGEXP_MATCH(Product Name,'(?i)Issey Miyake.*') THEN "Issey Miyake"
WHEN REGEXP_MATCH(Product Name,'(?i)Jimmy Choo.*') THEN "Jimmy Choo"
WHEN REGEXP_MATCH(Product Name,'(?i)Jo Malone.*') THEN "Jo Malone"
WHEN REGEXP_MATCH(Product Name,'(?i)Kenzo.*') THEN "Kenzo"
WHEN REGEXP_MATCH(Product Name,'(?i)Kérastase.*') THEN "Kérastase"
WHEN REGEXP_MATCH(Product Name,'(?i)Kiehl.*s.*') THEN "Kiehl's"
WHEN REGEXP_MATCH(Product Name,'(?i)L.*Occitane.*') THEN "L'Occitane"
WHEN REGEXP_MATCH(Product Name,'(?i)L.*Oreal.*') THEN "L'Oreal"
WHEN REGEXP_MATCH(Product Name,'(?i)La Mer.*') THEN "La Mer"
WHEN REGEXP_MATCH(Product Name,'(?i)La Prairie.*') THEN "La Prairie"
WHEN REGEXP_MATCH(Product Name,'(?i)Lancôme.*|(?i)lancome') THEN "Lancôme"
WHEN REGEXP_MATCH(Product Name,'(?i)Marc Jacobs.*') THEN "Marc Jacobs"
WHEN REGEXP_MATCH(Product Name,'(?i)Marvis.*') THEN "Marvis"
WHEN REGEXP_MATCH(Product Name,'(?i)Max Factor.*') THEN "Max Factor"
WHEN REGEXP_MATCH(Product Name,'(?i)Moroccanoil.*') THEN "Moroccan Oil"
WHEN REGEXP_MATCH(Product Name,'(?i)Moschino.*') THEN "Moschino"
WHEN REGEXP_MATCH(Product Name,'(?i)NuFace.*') THEN "NuFace"
WHEN REGEXP_MATCH(Product Name,'(?i)Nuxe.*') THEN "Nuxe"
WHEN REGEXP_MATCH(Product Name,'(?i)NYX.*') THEN "NYX"
WHEN REGEXP_MATCH(Product Name,'(?i)Olay.*') THEN "Olay"
WHEN REGEXP_MATCH(Product Name,'(?i)Omorovicza.*') THEN "Omorovicza"
WHEN REGEXP_MATCH(Product Name,'.*(?i)Origins.*') THEN "Origins"
WHEN REGEXP_MATCH(Product Name,'(?i)Pasotti.*') THEN "Pasotti"
WHEN REGEXP_MATCH(Product Name,'(?i)Philips.*') THEN "Philips"
WHEN REGEXP_MATCH(Product Name,'(?i)Prada.*') THEN "Prada"
WHEN REGEXP_MATCH(Product Name,'(?i)Ray-Ban.*') THEN "Ray-Ban"
WHEN REGEXP_MATCH(Product Name,'(?i)Real Techniques.*') THEN "Real Techniques"
WHEN REGEXP_MATCH(Product Name,'(?i)Revlon.*') THEN "Revlon"
WHEN REGEXP_MATCH(Product Name,'(?i)Salvatore Ferragamo.*') THEN "Salvatore Ferragamo"
WHEN REGEXP_MATCH(Product Name,'(?i)Serge Lutens.*') THEN "Serge Lutens"
WHEN REGEXP_MATCH(Product Name,'(?i)Shiseido.*') THEN "Shiseido"
WHEN REGEXP_MATCH(Product Name,'(?i)Sisley.*') THEN "Sisley"
WHEN REGEXP_MATCH(Product Name,'(?i)SK-II.*') THEN "SK-II"
WHEN REGEXP_MATCH(Product Name,'(?i)Stila.*') THEN "Stila"
WHEN REGEXP_MATCH(Product Name,'(?i)Swarovski.*') THEN "Swarovski"
WHEN REGEXP_MATCH(Product Name,'(?i)Tom Ford.*') THEN "Tom Ford"
WHEN REGEXP_MATCH(Product Name,'(?i)Trilogy.*') THEN "Trilogy"
WHEN REGEXP_MATCH(Product Name,'(?i)Valentino.*') THEN "Valentino"
WHEN REGEXP_MATCH(Product Name,'(?i)Valmont.*') THEN "Valmont"
WHEN REGEXP_MATCH(Product Name,'(?i)Versace.*') THEN "Versace"
WHEN REGEXP_MATCH(Product Name,'(?i)YSL.*') THEN "YSL"
WHEN REGEXP_MATCH(Product Name,'(?i)Ziaja.*') THEN "Ziaja"
END