CASE
WHEN REGEXP_MATCH(Product Name,'(?i)Anna Sui.*') THEN "Anna Sui"
WHEN REGEXP_MATCH(Product Name,'(?i)Emporio Armani.*') THEN "Emporio Armani"
WHEN REGEXP_MATCH(Product Name,'(?i)Acqua Di Parma.*') THEN "Acqua Di Parma"
WHEN REGEXP_MATCH(Product Name,'(?i)Ahava.*') THEN "Ahava"
WHEN REGEXP_MATCH(Product Name,'(?i)Anastasia.*|.*(?i)dipbrow pomade.*|.*(?i)Brow Wiz.*') THEN "Anastasia"

WHEN REGEXP_MATCH(Product Name,'(?i)Bulgari.*') THEN "Bulgari"
WHEN REGEXP_MATCH(Product Name,'.*(?i)Burberry.*') THEN "Burberry"
WHEN REGEXP_MATCH(Product Name,'(?i)By Terry.*') THEN "By Terry"
WHEN REGEXP_MATCH(Product Name,'(?i)Bio-Oil.*') THEN "Bio-Oil"
WHEN REGEXP_MATCH(Product Name,'(?i)BVLGARI.*') THEN "BVLGARI"
WHEN REGEXP_MATCH(Product Name,'(?i)Benefit.*') THEN "Benefit"
WHEN REGEXP_MATCH(Product Name,'(?i)Bellápierre.*|(?i)Bellapierre.*') THEN "Bellápierre"
WHEN REGEXP_MATCH(Product Name,'(?i)Biotherm.*') THEN "Biotherm"
WHEN REGEXP_MATCH(Product Name,'.*(?i)Bourjois.*') THEN "Bourjois"
WHEN REGEXP_MATCH(Product Name,'(?i)Bobbi Brown.*') THEN "Bobbi Brown"
WHEN REGEXP_MATCH(Product Name,'(?i)Bleach London.*') THEN "Bleach London"

WHEN REGEXP_MATCH(Product Name,'(?i)Calvin Klein.*') THEN "Calvin Klein"
WHEN REGEXP_MATCH(Product Name,'(?i)Chanel.*') THEN "Chanel"
WHEN REGEXP_MATCH(Product Name,'(?i)Chloe.*|(?i)Chloé.*') THEN "Chloe"
WHEN REGEXP_MATCH(Product Name,'(?i)Christophe Robin.*') THEN "Christophe Robin"
WHEN REGEXP_MATCH(Product Name,'(?i)Clarins.*') THEN "Clarins"
WHEN REGEXP_MATCH(Product Name,'(?i)Clarisonic.*') THEN "Clarisonic"
WHEN REGEXP_MATCH(Product Name,'.*(?i)Clinique.*') THEN "Clinique"
WHEN REGEXP_MATCH(Product Name,'(?i)Coach.*') THEN "Coach"
WHEN REGEXP_MATCH(Product Name,'(?i)Caudalie.*') THEN "Caudalie"
WHEN REGEXP_MATCH(Product Name,'(?i)CeraVe.*') THEN "CeraVe"
WHEN REGEXP_MATCH(Product Name,'(?i)Cath Kidston.*') THEN "Cath Kidston"

WHEN REGEXP_MATCH(Product Name,'.*(?i)Dior.*') THEN "Dior"
WHEN REGEXP_MATCH(Product Name,'(?i)Dolce.*Gabbana.*') THEN "Dolce & Gabbana"
WHEN REGEXP_MATCH(Product Name,'(?i)Dr.*Jart.*') THEN "Dr. Jart"
WHEN REGEXP_MATCH(Product Name,'(?i)Dove.*') THEN "Dove"

WHEN REGEXP_MATCH(Product Name,'(?i)Elizabeth Arden.*') THEN "Elizabeth Arden"
WHEN REGEXP_MATCH(Product Name,'(?i)Erno Laszlo.*') THEN "Erno Laszlo"
WHEN REGEXP_MATCH(Product Name,'(?i)Estée Lauder.*|(?i)estee lauder.*') THEN "Estée Lauder"
WHEN REGEXP_MATCH(Product Name,'(?i)Eve Lom.*') THEN "Eve Lom"
WHEN REGEXP_MATCH(Product Name,'(?i)Elta.*MD.*') THEN "EltaMD"

WHEN REGEXP_MATCH(Product Name,'(?i)Filorga.*') THEN "Filorga"
WHEN REGEXP_MATCH(Product Name,'(?i)Foreo.*') THEN "Foreo"
WHEN REGEXP_MATCH(Product Name,'(?i)Fresh.*') THEN "Fresh"
WHEN REGEXP_MATCH(Product Name,'(?i)Faith In Nature.*') THEN "Faith In Nature"
WHEN REGEXP_MATCH(Product Name,'(?i)Furla.*') THEN "Furla"

WHEN REGEXP_MATCH(Product Name,'(?i)GlamGlow.*') THEN "GlamGlow"
WHEN REGEXP_MATCH(Product Name,'(?i)Gucci.*') THEN "Gucci"
WHEN REGEXP_MATCH(Product Name,'(?i)Guerlain.*') THEN "Guerlain"
WHEN REGEXP_MATCH(Product Name,'(?i)Gweniss.*') THEN "Gweniss"
WHEN REGEXP_MATCH(Product Name,'(?i)Gretna Green.*') THEN "Gretna Green"
WHEN REGEXP_MATCH(Product Name,'(?i)Glencroft.*') THEN "Glencroft"
WHEN REGEXP_MATCH(Product Name,'(?i)Garnier.*') THEN "Garnier"
WHEN REGEXP_MATCH(Product Name,'(?i)Giorgio Armani.*|(?i)Armani.*') THEN "Giorgio Armani"
WHEN REGEXP_MATCH(Product Name,'(?i)Givenchy.*') THEN "Givenchy"

WHEN REGEXP_MATCH(Product Name,'(?i)Hermès.*') THEN "Hermes"
WHEN REGEXP_MATCH(Product Name,'(?i)Hortons.*') THEN "Hortons"

WHEN REGEXP_MATCH(Product Name,'(?i)Issey Miyake.*') THEN "Issey Miyake"
WHEN REGEXP_MATCH(Product Name,'(?i)IPSA.*') THEN "IPSA"

WHEN REGEXP_MATCH(Product Name,'(?i)Jimmy Choo.*') THEN "Jimmy Choo"
WHEN REGEXP_MATCH(Product Name,'(?i)Jo Malone.*') THEN "Jo Malone"

WHEN REGEXP_MATCH(Product Name,'(?i)Kenzo.*') THEN "Kenzo"
WHEN REGEXP_MATCH(Product Name,'(?i)Kérastase.*') THEN "Kérastase"
WHEN REGEXP_MATCH(Product Name,'(?i)Kiehl.*s.*') THEN "Kiehl's"

WHEN REGEXP_MATCH(Product Name,'.*(?i)L.*Occitane.*') THEN "L'Occitane"
WHEN REGEXP_MATCH(Product Name,'(?i)L.*Oreal.*|(?i)L.*Oréal.*') THEN "L'Oreal"
WHEN REGEXP_MATCH(Product Name,'(?i)La Mer.*') THEN "La Mer"
WHEN REGEXP_MATCH(Product Name,'(?i)La Prairie.*') THEN "La Prairie"
WHEN REGEXP_MATCH(Product Name,'(?i)Lancôme.*|(?i)lancome.*') THEN "Lancome"
WHEN REGEXP_MATCH(Product Name,'(?i)Living Proof.*') THEN "Living Proof"
WHEN REGEXP_MATCH(Product Name,'(?i)Laneige.*') THEN "Laneige"

WHEN REGEXP_MATCH(Product Name,'(?i)Marc Jacobs.*') THEN "Marc Jacobs"
WHEN REGEXP_MATCH(Product Name,'.*(?i)Marvis.*') THEN "Marvis"
WHEN REGEXP_MATCH(Product Name,'(?i)Max Factor.*') THEN "Max Factor"
WHEN REGEXP_MATCH(Product Name,'(?i)Moroccanoil.*|(?i)MorrocanOil.*') THEN "Moroccan Oil"
WHEN REGEXP_MATCH(Product Name,'(?i)Moschino.*') THEN "Moschino"
WHEN REGEXP_MATCH(Product Name,'(?i)MAC.*') THEN "MAC"
WHEN REGEXP_MATCH(Product Name,'(?i)Michael Kors.*') THEN "Michael Kors"
WHEN REGEXP_MATCH(Product Name,'(?i)Miu Miu.*') THEN "Miu Miu"

WHEN REGEXP_MATCH(Product Name,'(?i)NuFace.*') THEN "NuFace"
WHEN REGEXP_MATCH(Product Name,'(?i)Nuxe.*') THEN "Nuxe"
WHEN REGEXP_MATCH(Product Name,'(?i)NYX.*') THEN "NYX"
WHEN REGEXP_MATCH(Product Name,'(?i)Natura Bissé.*|(?i)|Natura Bisse.*') THEN "Natura Bisse"
WHEN REGEXP_MATCH(Product Name,'(?i)Nails Inc.*') THEN "Nails Inc"
WHEN REGEXP_MATCH(Product Name,'(?i)Nioxin.*') THEN "Nioxin"

WHEN REGEXP_MATCH(Product Name,'(?i)Olay.*') THEN "Olay"
WHEN REGEXP_MATCH(Product Name,'(?i)Omorovicza.*') THEN "Omorovicza"
WHEN REGEXP_MATCH(Product Name,'.*(?i)Origins.*') THEN "Origins"
WHEN REGEXP_MATCH(Product Name,'(?i)Oral B.*') THEN "Oral B"
WHEN REGEXP_MATCH(Product Name,'O.P.I.*|OPI.*') THEN "O.P.I"

WHEN REGEXP_MATCH(Product Name,'(?i)Pasotti.*') THEN "Pasotti"
WHEN REGEXP_MATCH(Product Name,'.*(?i)Philips.*') THEN "Philips"
WHEN REGEXP_MATCH(Product Name,'(?i)Prada.*') THEN "Prada"
WHEN REGEXP_MATCH(Product Name,'(?i)Philosophy.*') THEN "Philosophy"
WHEN REGEXP_MATCH(Product Name,'(?i)Penhaligon.*s.*') THEN "Penhaligon's"
WHEN REGEXP_MATCH(Product Name,'(?i)Philip Kingsley.*') THEN "Philip Kingsley"
WHEN REGEXP_MATCH(Product Name,'(?i)Paco Rabanne.*') THEN "Paco Rabanne"
WHEN REGEXP_MATCH(Product Name,'(?i)Perricone MD.*') THEN "Perricone MD"
WHEN REGEXP_MATCH(Product Name,'(?i)Playboy.*') THEN "Playboy"
WHEN REGEXP_MATCH(Product Name,'(?i)Pixi.*') THEN "Pixi"

WHEN REGEXP_MATCH(Product Name,'(?i)Ray-Ban.*') THEN "Ray-Ban"
WHEN REGEXP_MATCH(Product Name,'(?i)Real Technique.*') THEN "Real Techniques"
WHEN REGEXP_MATCH(Product Name,'(?i)Revlon.*') THEN "Revlon"
WHEN REGEXP_MATCH(Product Name,'(?i)Paul Smith.*') THEN "Paul Smith"
WHEN REGEXP_MATCH(Product Name,'(?i)REN.*') THEN "REN"

WHEN REGEXP_MATCH(Product Name,'(?i)Salvatore Ferragamo.*') THEN "Salvatore Ferragamo"
WHEN REGEXP_MATCH(Product Name,'(?i)Serge Lutens.*') THEN "Serge Lutens"
WHEN REGEXP_MATCH(Product Name,'(?i)Shiseido.*') THEN "Shiseido"
WHEN REGEXP_MATCH(Product Name,'(?i)Sisley.*') THEN "Sisley"
WHEN REGEXP_MATCH(Product Name,'(?i)SK-II.*') THEN "SK-II"
WHEN REGEXP_MATCH(Product Name,'(?i)Stila.*') THEN "Stila"
WHEN REGEXP_MATCH(Product Name,'.*(?i)Swarovski.*') THEN "Swarovski"
WHEN REGEXP_MATCH(Product Name,'(?i)Sulwhasoo.*') THEN "Sulwhasoo"
WHEN REGEXP_MATCH(Product Name,'(?i)Stella McCartney.*') THEN "Stella McCartney"
WHEN REGEXP_MATCH(Product Name,'(?i)Sebastian.*') THEN "Sebastian"


WHEN REGEXP_MATCH(Product Name,'(?i)Tom Ford.*') THEN "Tom Ford"
WHEN REGEXP_MATCH(Product Name,'(?i)Trilogy.*') THEN "Trilogy"
WHEN REGEXP_MATCH(Product Name,'(?i)Tangle Teezer.*') THEN "Tangle Teezer"
WHEN REGEXP_MATCH(Product Name,'(?i)Tangle Angel.*') THEN "Tangle Angel"
WHEN REGEXP_MATCH(Product Name,'(?i)The Body Shop.*') THEN "The Body Shop"
WHEN REGEXP_MATCH(Product Name,'(?i)Tissot.*') THEN "Tissot"
WHEN REGEXP_MATCH(Product Name,'TIGI.*') THEN "TIGI"
WHEN REGEXP_MATCH(Product Name,'(?i)Trussardi.*') THEN "Trussardi"
WHEN REGEXP_MATCH(Product Name,'(?i)Thalgo.*') THEN "Thalgo"
WHEN REGEXP_MATCH(Product Name,'(?i)This Works.*') THEN "This Works"

WHEN REGEXP_MATCH(Product Name,'(?i)Urban Decay.*') THEN "Urban Decay"
WHEN REGEXP_MATCH(Product Name,'(?i)Unineed.*|.*(?i)Reshipment Fee.*|.*(?i)Re-Shipment.*') THEN "Unineed"

WHEN REGEXP_MATCH(Product Name,'(?i)Valentino.*') THEN "Valentino"
WHEN REGEXP_MATCH(Product Name,'(?i)Valmont.*') THEN "Valmont"
WHEN REGEXP_MATCH(Product Name,'(?i)Versace.*') THEN "Versace"
WHEN REGEXP_MATCH(Product Name,'(?i)Vera Wang.*') THEN "Vera Wang"
WHEN REGEXP_MATCH(Product Name,'(?i)Van Cleef.*') THEN "Van Cleef and Arpels"
WHEN REGEXP_MATCH(Product Name,'(?i)Vichy.*') THEN "Vichy"

WHEN REGEXP_MATCH(Product Name,'(?i)Warmies.*') THEN "Warmies"
WHEN REGEXP_MATCH(Product Name,'(?i)Woods Of Windsor.*') THEN "Woods Of Windsor"

WHEN REGEXP_MATCH(Product Name,'(?i)YSL|Yves Saint Laurent.*') THEN "YSL"

WHEN REGEXP_MATCH(Product Name,'(?i)Ziaja.*') THEN "Ziaja"
END